CREATE OR REPLACE VIEW "TWITTER_ADS_VIEWS"."ENTITY_SCHEDULED_PROMOTED_TWEETS" AS

SELECT 

	ID::VARCHAR(256)                  AS SCHEDULED_PROMOTED_TWEET_ID
	, UPDATED_AT::TIMESTAMP_TZ(9)       AS UPDATED_AT
	, LINE_ITEM_ID::VARCHAR(256)        AS LINE_ITEM_ID
	, SCHEDULED_TWEET_ID::VARCHAR(256)  AS SCHEDULED_TWEET_ID
	, TWEET_ID::VARCHAR(256)            AS TWEET_ID
	, CREATED_AT::TIMESTAMP_TZ(9)       AS CREATED_AT
	, DELETED::BOOLEAN                  AS DELETED
	, _FIVETRAN_SYNCED::TIMESTAMP_TZ(9) AS _FIVETRAN_SYNCED

FROM (

  SELECT *
    , ROW_NUMBER() OVER (PARTITION BY ID ORDER BY _FIVETRAN_SYNCED DESC) ___R
  FROM "TWITTER_ADS"."SCHEDULED_PROMOTED_TWEETS_HISTORY"

) DT
WHERE DT.___R = 1
;