CREATE OR REPLACE VIEW "TWITTER_ADS_VIEWS"."ENTITY_TWEET_MEDIA" AS

SELECT 

	TWEET_ID::VARCHAR(256)              AS TWEET_ID
	, MEDIA_ID::VARCHAR(256)            AS MEDIA_ID
	, INDICES::VARIANT                  AS MEDIA_INDICES
	, MEDIA_URL::VARCHAR(256)           AS MEDIA_URL
	, MEDIA_URL_HTTPS::VARCHAR(256)     AS MEDIA_URL_HTTPS
	, URL::VARCHAR(256)                 AS URL
	, DISPLAY_URL::VARCHAR(256)         AS DISPLAY_URL
	, EXPANDED_URL::VARCHAR(256)        AS EXPANDED_URL
	, TYPE::VARCHAR(256)                AS MEDIA_TYPE
	, SIZES::VARIANT                    AS SIZES
	, _FIVETRAN_SYNCED::TIMESTAMP_TZ(9) AS _FIVETRAN_SYNCED

FROM "TWITTER_ADS"."TWEET_MEDIA"
;

