CREATE OR REPLACE VIEW "TWITTER_ADS_VIEWS"."ENTITY_TWEETS" AS

SELECT 

	ID::VARCHAR(256)                        AS TWEET_ID
	, ACCOUNT_ID::VARCHAR(256)              AS ACCOUNT_ID
	, CREATED_AT::TIMESTAMP_TZ(9)           AS CREATED_AT
	, FULL_TEXT::VARCHAR(1024)              AS FULL_TEXT
	, TRUNCATED::BOOLEAN                    AS TRUNCATED
	, SOURCE::VARCHAR(256)                  AS SOURCE
	, IN_REPLY_TO_STATUS_ID::VARCHAR(256)   AS IN_REPLY_TO_STATUS_ID
	, IN_REPLY_TO_USER_ID::VARCHAR(256)     AS IN_REPLY_TO_USER_ID
	, IN_REPLY_TO_SCREEN_NAME::VARCHAR(256) AS IN_REPLY_TO_SCREEN_NAME
	, RETWEET_COUNT::NUMBER(38,0)           AS RETWEET_COUNT
	, FAVORITE_COUNT::NUMBER(38,0)          AS FAVORITE_COUNT
	, FAVORITED::BOOLEAN                    AS FAVORITED
	, RETWEETED::BOOLEAN                    AS RETWEETED
	, LANG::VARCHAR(256)                    AS LANG
	, TWEET_TYPE::VARCHAR(256)              AS TWEET_TYPE
	, MEDIA_KEY::VARCHAR(256)               AS MEDIA_KEY
	, CARD_URI::VARCHAR(256)                AS CARD_URI
	, GEO_TYPE::VARCHAR(256)                AS GEO_TYPE
	, GEO_COORDINATES::VARIANT              AS GEO_COORDINATES
	, COORDINATES_TYPE::VARCHAR(256)        AS COORDINATES_TYPE
	, COORDINATES_COORDINATES::VARIANT      AS COORDINATES_COORDINATES
	, FOLLOWERS::BOOLEAN                    AS FOLLOWERS
	, USER_ID::VARCHAR(256)                 AS USER_ID
	, _FIVETRAN_SYNCED::TIMESTAMP_TZ(9)     AS _FIVETRAN_SYNCED

FROM "TWITTER_ADS"."TWEET"
;

