CREATE OR REPLACE VIEW "TWITTER_ADS_VIEWS"."ENTITY_FUNDING_INSTRUMENTS" AS

SELECT 

	ID::VARCHAR(256)                              AS FUNDING_INSTRUMENT_ID
	, UPDATED_AT::TIMESTAMP_TZ(9)                   AS UPDATED_AT
	, ACCOUNT_ID::VARCHAR(256)                      AS ACCOUNT_ID
	, START_TIME::TIMESTAMP_TZ(9)                   AS START_TIME
	, DESCRIPTION::VARCHAR(256)                     AS DESCRIPTION
	, CREDIT_LIMIT_LOCAL_MICRO::NUMBER(38,0)        AS CREDIT_LIMIT_LOCAL_MICRO
	, END_TIME::TIMESTAMP_TZ(9)                     AS END_TIME
	, ENTITY_STATUS::VARCHAR(256)                   AS ENTITY_STATUS
	, IO_HEADER::VARCHAR(256)                       AS IO_HEADER
	, CURRENCY::VARCHAR(256)                        AS CURRENCY
	, FUNDED_AMOUNT_LOCAL_MICRO::NUMBER(38,0)       AS FUNDED_AMOUNT_LOCAL_MICRO
	, CREATED_AT::TIMESTAMP_TZ(9)                   AS CREATED_AT
	, TYPE::VARCHAR(256)                            AS FUNDING_INSTRUMENT_TYPE
	, ABLE_TO_FUND::BOOLEAN                         AS ABLE_TO_FUND
	, CREDIT_REMAINING_LOCAL_MICRO::NUMBER(38,0)    AS CREDIT_REMAINING_LOCAL_MICRO
	, DELETED::BOOLEAN                              AS DELETED
	, _FIVETRAN_SYNCED::TIMESTAMP_TZ(9)             AS _FIVETRAN_SYNCED

FROM (

  SELECT *
    , ROW_NUMBER() OVER (PARTITION BY ID, ACCOUNT_ID ORDER BY _FIVETRAN_SYNCED DESC) ___R
  FROM "TWITTER_ADS"."FUNDING_INSTRUMENT_HISTORY"

) DT
WHERE DT.___R = 1
;
