CREATE OR REPLACE VIEW "TWITTER_ADS_VIEWS"."ENTITY_CAMPAIGNS" AS

SELECT 

  ID::VARCHAR(256)                                  AS CAMPAIGN_ID
  , ACCOUNT_ID::VARCHAR(256)                        AS ACCOUNT_ID
  , FUNDING_INSTRUMENT_ID::VARCHAR(256)             AS FUNDING_INSTRUMENT_ID
  , NAME::VARCHAR(256)                              AS CAMPAIGN_NAME
  , START_TIME::TIMESTAMP_TZ(9)                     AS START_TIME
  , END_TIME::TIMESTAMP_TZ(9)                       AS END_TIME
  , SERVABLE::BOOLEAN                               AS SERVABLE
  , TOTAL_BUDGET_AMOUNT_LOCAL_MICRO::NUMBER(38,0)   AS TOTAL_BUDGET_AMOUNT_LOCAL_MICRO
  , DAILY_BUDGET_AMOUNT_LOCAL_MICRO::NUMBER(38,0)   AS DAILY_BUDGET_AMOUNT_LOCAL_MICRO
  , DURATION_IN_DAYS::NUMBER(38,0)                  AS DURATION_IN_DAYS
  , STANDARD_DELIVERY::BOOLEAN                      AS STANDARD_DELIVERY
  , ENTITY_STATUS::VARCHAR(256)                     AS ENTITY_STATUS
  , FREQUENCY_CAP::NUMBER(38,0)                     AS FREQUENCY_CAP
  , CURRENCY::VARCHAR(256)                          AS CURRENCY
  , CREATED_AT::TIMESTAMP_TZ(9)                     AS CREATED_AT
  , UPDATED_AT::TIMESTAMP_TZ(9)                     AS UPDATED_AT
  , DELETED::BOOLEAN                                AS DELETED
  , _FIVETRAN_SYNCED::TIMESTAMP_TZ(9)               AS _FIVETRAN_SYNCED

FROM (

  SELECT *
    , ROW_NUMBER() OVER (PARTITION BY ID, ACCOUNT_ID ORDER BY _FIVETRAN_SYNCED DESC) ___R
  FROM "TWITTER_ADS"."CAMPAIGN_HISTORY"

) DT
WHERE DT.___R = 1
;
