CREATE OR REPLACE VIEW "TWITTER_ADS_VIEWS"."ENTITY_PROMOTED_TWEETS" AS

SELECT 

	ID::VARCHAR(256)                    AS PROMOTED_TWEET_ID
	, UPDATED_AT::TIMESTAMP_TZ(9)       AS UPDATED_AT
	, LINE_ITEM_ID::VARCHAR(256)        AS LINE_ITEM_ID
	, TWEET_ID::VARCHAR(256)            AS TWEET_ID
	, ENTITY_STATUS::VARCHAR(256)       AS ENTITY_STATUS
	, CREATED_AT::TIMESTAMP_TZ(9)       AS CREATED_AT
	, APPROVAL_STATUS::VARCHAR(256)     AS APPROVAL_STATUS
	, DELETED::BOOLEAN                  AS DELETED
	, _FIVETRAN_SYNCED::TIMESTAMP_TZ(9) AS _FIVETRAN_SYNCED

FROM (

  SELECT *
    , ROW_NUMBER() OVER (PARTITION BY ID ORDER BY _FIVETRAN_SYNCED DESC) ___R
  FROM "TWITTER_ADS"."PROMOTED_TWEET_HISTORY"

) DT
WHERE DT.___R = 1
;

