CREATE OR REPLACE VIEW "TWITTER_ADS_VIEWS"."ENTITY_ACCOUNTS" AS

SELECT 

  ID::VARCHAR(256)                              AS ACCOUNT_ID
  , NAME::VARCHAR(256)                          AS ACCOUNT_NAME
  , UPDATED_AT::TIMESTAMP_TZ(9)                 AS UPDATED_AT
  , BUSINESS_NAME::VARCHAR(256)                 AS BUSINESS_NAME
  , TIMEZONE::VARCHAR(256)                      AS TIMEZONE
  , TIMEZONE_SWITCH_AT::TIMESTAMP_TZ(9)         AS TIMEZONE_SWITCH_AT    
  , CREATED_AT::TIMESTAMP_TZ(9)                 AS CREATED_AT
  , SALT::VARCHAR(256)                          AS SALT
  , BUSINESS_ID::VARCHAR(256)                   AS BUSINESS_ID
  , APPROVAL_STATUS::VARCHAR(256)               AS APPROVAL_STATUS
  , DELETED::BOOLEAN                            AS DELETED
  , INDUSTRY_TYPE::VARCHAR(256)                 AS INDUSTRY_TYPE
  , _FIVETRAN_SYNCED::TIMESTAMP_TZ(9)           AS _FIVETRAN_SYNCED

FROM (

  SELECT *
    , ROW_NUMBER() OVER (PARTITION BY ID ORDER BY _FIVETRAN_SYNCED DESC) ___R
  FROM "TWITTER_ADS"."ACCOUNT_HISTORY"

) DT
WHERE DT.___R = 1
;
