CREATE OR REPLACE VIEW "TWITTER_ADS_VIEWS"."ENTITY_TWEET_URLS" AS

SELECT 

	TWEET_ID::VARCHAR(256)              AS TWEET_ID
	, INDEX::NUMBER(38,0)               AS URL_INDEX
	, URL::VARCHAR(256)                 AS URL
	, EXPANDED_URL::VARCHAR(512)        AS EXPANDED_URL
	, DISPLAY_URL::VARCHAR(256)         AS DISPLAY_URL
	, INDICES::VARIANT                  AS URL_INDICES
	, _FIVETRAN_SYNCED::TIMESTAMP_TZ(9) AS _FIVETRAN_SYNCED

FROM "TWITTER_ADS"."TWEET_URL"
;

