CREATE OR REPLACE VIEW "TWITTER_ADS_VIEWS"."ENTITY_ACCOUNT_MEDIA" AS

SELECT 

  ID::VARCHAR(256)                              AS MEDIA_ID
  , ACCOUNT_ID::VARCHAR(256)                    AS ACCOUNT_ID
  , UPDATED_AT::TIMESTAMP_TZ(9)                 AS UPDATED_AT   
  , CREATED_AT::TIMESTAMP_TZ(9)                 AS CREATED_AT
  , DELETED::BOOLEAN                            AS DELETED
  , MEDIA_KEY::VARCHAR(256)                     AS MEDIA_KEY
  , MEDIA_URL::VARCHAR(256)                     AS MEDIA_URL
  , CREATIVE_TYPE::VARCHAR(256)                 AS CREATIVE_TYPE
  , VAST_URL::VARCHAR(256)                      AS VAST_URL
  , _FIVETRAN_SYNCED::TIMESTAMP_TZ(9)           AS _FIVETRAN_SYNCED

FROM (

  SELECT *
    , ROW_NUMBER() OVER (PARTITION BY ID, ACCOUNT_ID ORDER BY _FIVETRAN_SYNCED DESC) ___R
  FROM "TWITTER_ADS"."ACCOUNT_MEDIA_HISTORY"

) DT
WHERE DT.___R = 1
;
