CREATE OR REPLACE VIEW "TWITTER_ADS_VIEWS"."ENTITY_SCHEDULED_TWEETS" AS

SELECT 

	ID::VARCHAR(256)                  AS SCHEDULED_TWEET_ID
	, UPDATED_AT::TIMESTAMP_TZ(9)       AS UPDATED_AT
	, COMPLETED_AT::TIMESTAMP_TZ(9)     AS COMPLETED_AT
	, CARD_URI::VARCHAR(256)            AS CARD_URI
	, TEXT::VARCHAR(512)                AS TEXT
	, USER_ID::VARCHAR(256)             AS USER_ID
	, SCHEDULED_STATUS::VARCHAR(256)    AS SCHEDULED_STATUS
	, NULLCAST::BOOLEAN                 AS NULLCAST
	, CREATED_AT::TIMESTAMP_TZ(9)       AS CREATED_AT
	, SCHEDULED_AT::TIMESTAMP_TZ(9)     AS SCHEDULED_AT
	, TWEET_ID::VARCHAR(256)            AS TWEET_ID
	, ACCOUNT_ID::VARCHAR(256)          AS ACCOUNT_ID
	, _FIVETRAN_SYNCED::TIMESTAMP_TZ(9) AS _FIVETRAN_SYNCED

FROM (

  SELECT *
    , ROW_NUMBER() OVER (PARTITION BY ID ORDER BY _FIVETRAN_SYNCED DESC) ___R
  FROM "TWITTER_ADS"."SCHEDULED_TWEET_HISTORY"

) DT
WHERE DT.___R = 1
;