CREATE OR REPLACE VIEW "TWITTER_ADS_VIEWS"."ENTITY_LINE_ITEMS" AS

SELECT 

	ID::VARCHAR(256)                                  AS LINE_ITEM_ID
	, UPDATED_AT::TIMESTAMP_TZ(9)                       AS UPDATED_AT
	, CAMPAIGN_ID::VARCHAR(256)                         AS CAMPAIGN_ID
	, BID_TYPE::VARCHAR(256)                            AS BID_TYPE
	, ADVERTISER_USER_ID::NUMBER(38,0)                  AS ADVERTISER_USER_ID
	, NAME::VARCHAR(256)                                AS LINE_ITEM_NAME
	, START_TIME::TIMESTAMP_TZ(9)                       AS START_TIME
	, BID_AMOUNT_LOCAL_MICRO::NUMBER(38,0)              AS BID_AMOUNT_LOCAL_MICRO
	, AUTOMATICALLY_SELECT_BID::BOOLEAN                 AS AUTOMATICALLY_SELECT_BID
	, ADVERTISER_DOMAIN::VARCHAR(256)                   AS ADVERTISER_DOMAIN
	, TARGET_CPA_LOCAL_MICRO::NUMBER(38,0)              AS TARGET_CPA_LOCAL_MICRO
	, PRIMARY_WEB_EVENT_TAG::VARCHAR(256)               AS PRIMARY_WEB_EVENT_TAG
	, CHARGE_BY::VARCHAR(256)                           AS CHARGE_BY
	, PRODUCT_TYPE::VARCHAR(256)                        AS PRODUCT_TYPE
	, END_TIME::TIMESTAMP_TZ(9)                         AS END_TIME
	, BID_UNIT::VARCHAR(256)                            AS BID_UNIT
	, TOTAL_BUDGET_AMOUNT_LOCAL_MICRO::NUMBER(38,0)     AS TOTAL_BUDGET_AMOUNT_LOCAL_MICRO
	, OBJECTIVE::VARCHAR(256)                           AS OBJECTIVE
	, ENTITY_STATUS::VARCHAR(256)                       AS ENTITY_STATUS
	, OPTIMIZATION::VARCHAR(256)                        AS OPTIMIZATION
	, CURRENCY::VARCHAR(256)                            AS CURRENCY
	, CREATED_AT::TIMESTAMP_TZ(9)                       AS CREATED_AT
	, CREATIVE_SOURCE::VARCHAR(256)                     AS CREATIVE_SOURCE
	, DELETED::BOOLEAN                                  AS DELETED
	, _FIVETRAN_SYNCED::TIMESTAMP_TZ(9)                 AS _FIVETRAN_SYNCED

FROM (

  SELECT *
    , ROW_NUMBER() OVER (PARTITION BY ID ORDER BY _FIVETRAN_SYNCED DESC) ___R
  FROM "PC_FIVETRAN_DB"."TWITTER_ADS"."LINE_ITEM_HISTORY"

) DT
WHERE DT.___R = 1
;
