CREATE OR REPLACE VIEW "TWITTER_ADS_VIEWS"."ENTITY_MEDIA_LIBRARY" AS

SELECT 

	MEDIA_KEY::VARCHAR(256)             AS MEDIA_KEY
	, UPDATED_AT::TIMESTAMP_TZ(9)       AS UPDATED_AT
	, TWEETED::BOOLEAN                  AS TWEETED
	, NAME::VARCHAR(256)                AS NAME
	, FILE_NAME::VARCHAR(256)           AS FILE_NAME
	, MEDIA_URL::VARCHAR(256)           AS MEDIA_URL
	, MEDIA_CATEGORY::VARCHAR(256)      AS MEDIA_CATEGORY
	, CREATED_AT::TIMESTAMP_TZ(9)       AS CREATED_AT
	, MEDIA_STATUS::VARCHAR(256)        AS MEDIA_STATUS
	, MEDIA_TYPE::VARCHAR(256)          AS MEDIA_TYPE
	, DELETED::BOOLEAN                  AS DELETED
	, ORIGINAL_WIDTH::NUMBER(38,0)      AS ORIGINAL_WIDTH
	, ORIGINAL_HEIGHT::NUMBER(38,0)     AS ORIGINAL_HEIGHT
	, POSTER_MEDIA_KEY::VARCHAR(256)    AS POSTER_MEDIA_KEY
	, POSTER_MEDIA_URL::VARCHAR(256)    AS POSTER_MEDIA_URL
	, _FIVETRAN_SYNCED::TIMESTAMP_TZ(9) AS _FIVETRAN_SYNCED

FROM "TWITTER_ADS"."MEDIA_LIBRARY"
;