CREATE OR REPLACE VIEW "TWITTER_ADS_VIEWS"."METRIC_ACCOUNT_DAILY" AS

SELECT 

	ACCOUNT_ID::VARCHAR(256)            AS ACCOUNT_ID
	, DATE::TIMESTAMP_TZ(9)             AS DATE
	, PLACEMENT::VARCHAR(256)           AS PLACEMENT
	, REPLIES::NUMBER(38,0)             AS REPLIES
	, FOLLOWS::NUMBER(38,0)             AS FOLLOWS
	, ENGAGEMENTS::NUMBER(38,0)         AS ENGAGEMENTS
	, IMPRESSIONS::NUMBER(38,0)         AS IMPRESSIONS
	, UNFOLLOWS::NUMBER(38,0)           AS UNFOLLOWS
	, RETWEETS::NUMBER(38,0)            AS RETWEETS
	, LIKES::NUMBER(38,0)               AS LIKES
	, _FIVETRAN_SYNCED::TIMESTAMP_TZ(9) AS _FIVETRAN_SYNCED

FROM "TWITTER_ADS"."ACCOUNT_REPORT"
;

