CREATE OR REPLACE VIEW PINTEREST_VIEWS.ENTITY_AUDIENCES AS
SELECT
    ID,
    ADVERTISER_ID,
    NAME,
    STATUS,
    DESCRIPTION,
    RULE,
    AUDIENCE_TYPE,
    SIZE,
    __PROCESSED_AT
 FROM (
SELECT ID::VARCHAR AS ID,
       ADVERTISER_ID::VARCHAR AS ADVERTISER_ID,
       NAME::VARCHAR AS NAME,
       STATUS::VARCHAR AS STATUS,
       DESCRIPTION::VARCHAR AS DESCRIPTION,
       RULE::VARCHAR AS RULE,
       AUDIENCE_TYPE::VARCHAR AS AUDIENCE_TYPE,
       SIZE::NUMBER(38,0) AS SIZE,
       _FIVETRAN_SYNCED::TIMESTAMP_TZ AS __PROCESSED_AT,
       -- this is temporary hotfix to avoid data discrepancy - duplicates in entity tables
       ROW_NUMBER() OVER (PARTITION BY ID ORDER BY _FIVETRAN_SYNCED DESC) AS ROW_NUM
FROM "PINTEREST_ADS_1"."AUDIENCE_HISTORY")
WHERE ROW_NUM = 1
;