CREATE OR REPLACE VIEW PINTEREST_VIEWS.ENTITY_CAMPAIGNS AS
SELECT
 ID,
 NAME,
 ADVERTISER_ID,
 STATUS,
 PRODUCT_FILTER,
 ORDER_LINE_ID,
 LIFETIME_SPEND_CAP,
 OPTIMIZATION_GOAL,
 DAILY_SPEND_CAP,
 CREATED_AT,
 UPDATED_AT,
 OBJECTIVE_TYPE
FROM (
       SELECT ID::VARCHAR AS ID,
              NAME::VARCHAR AS NAME,
              ADVERTISER_ID::VARCHAR AS ADVERTISER_ID,
              STATUS::VARCHAR AS STATUS,
              PRODUCT_FILTER::VARCHAR AS PRODUCT_FILTER,
              ORDER_LINE_ID::VARCHAR AS ORDER_LINE_ID,
              LIFETIME_SPEND_CAP::NUMBER(38,0) AS LIFETIME_SPEND_CAP,
              OPTIMIZATION_GOAL::VARCHAR AS OPTIMIZATION_GOAL,
              DAILY_SPEND_CAP::NUMBER(38,0) AS DAILY_SPEND_CAP,
              CREATED_TIME::TIMESTAMP_TZ AS CREATED_AT,
              UPDATED_TIME::TIMESTAMP_TZ AS UPDATED_AT,
              COALESCE(OBJECTIVE_TYPE::VARCHAR, OPTIMIZATION_GOAL::VARCHAR)  AS OBJECTIVE_TYPE,
              -- this is temporary hotfix to avoid data discrepancy - duplicates in entity tables
              ROW_NUMBER() OVER (PARTITION BY ID ORDER BY _FIVETRAN_SYNCED DESC) AS ROW_NUM
       FROM "PINTEREST_ADS_1"."CAMPAIGN_HISTORY"
)
WHERE ROW_NUM = 1
;