CREATE OR REPLACE VIEW PINTEREST_VIEWS.ENTITY_PIN_PROMOTIONS AS
SELECT
    ID,
    AD_GROUP_ID,
    NAME,
    PIN_ID,
    REVIEW_STATUS,
    STATUS,
    ANDROID_DEEP_LINK,
    IOS_DEEP_LINK,
    VIEW_TRACKING_URL,
    CLICK_TRACKING_URL,
    DESTINATION_URL,
    IS_PIN_DELETED,
    IS_REMOVABLE,
    CREATED_AT,
    UPDATED_AT,
    CREATIVE_TYPE
FROM (
  SELECT ID::VARCHAR AS ID,
         AD_GROUP_ID::VARCHAR AS AD_GROUP_ID,
         NAME::VARCHAR AS NAME,
         PIN_ID::VARCHAR AS PIN_ID,
         REVIEW_STATUS::VARCHAR AS REVIEW_STATUS,
         STATUS::VARCHAR AS STATUS,
         ANDROID_DEEP_LINK::VARCHAR AS ANDROID_DEEP_LINK,
         IOS_DEEP_LINK::VARCHAR AS IOS_DEEP_LINK,
         VIEW_TRACKING_URL::VARCHAR AS VIEW_TRACKING_URL,
         CLICK_TRACKING_URL::VARCHAR AS CLICK_TRACKING_URL,
         DESTINATION_URL::VARCHAR AS DESTINATION_URL,
         IS_PIN_DELETED::BOOLEAN AS IS_PIN_DELETED,
         IS_REMOVABLE::BOOLEAN AS IS_REMOVABLE,
         CREATED_TIME::TIMESTAMP_TZ AS CREATED_AT,
         UPDATED_TIME::TIMESTAMP_TZ AS UPDATED_AT,
         CREATIVE_TYPE::VARCHAR AS CREATIVE_TYPE,
         -- this is temporary hotfix to avoid data discrepancy - duplicates in entity tables
         ROW_NUMBER() OVER (PARTITION BY ID ORDER BY UPDATED_AT DESC) AS ROW_NUM
  FROM "PINTEREST_ADS_1"."PIN_PROMOTION_HISTORY"
)
WHERE ROW_NUM = 1
;