
CREATE OR REPLACE VIEW PINTEREST_VIEWS.ENTITY_ADGROUPS AS
SELECT
    ID,
    CAMPAIGN_ID,
    NAME,
    STATUS,
    UPGRADE_STATUS,
    LIFETIME_FREQUENCY_CAP,
    BUDGET_TYPE,
    BID_IN_MICRO_CURRENCY,
    BUDGET_IN_MICRO_CURRENCY,
    START_TIME,
    END_TIME,
    AUTO_TARGETING_ENABLED,
    TARGETING_SPEC_INTEREST,
    TARGETING_SPEC_LOCATION,
    TARGETING_SPEC_AUDIENCE_INCLUDE,
    TARGETING_SPEC_GENDER,
    TARGETING_SPEC_LOCALE,
    TARGETING_SPEC_APPTYPE,
    TARGETING_SPEC_AGE_BUCKET,
    CREATED_AT,
    UPDATED_AT
 FROM (
SELECT ID::VARCHAR AS ID,
       CAMPAIGN_ID::VARCHAR AS CAMPAIGN_ID,
       NAME::VARCHAR AS NAME,
       STATUS::VARCHAR AS STATUS,
       UPGRADE_STATUS::VARCHAR AS UPGRADE_STATUS,
       LIFETIME_FREQUENCY_CAP::NUMBER(38,0) AS LIFETIME_FREQUENCY_CAP,
       BUDGET_TYPE::VARCHAR AS BUDGET_TYPE,
       BID_IN_MICRO_CURRENCY::NUMBER(38,0) AS BID_IN_MICRO_CURRENCY,
       BUDGET_IN_MICRO_CURRENCY::NUMBER(38,0) AS BUDGET_IN_MICRO_CURRENCY,
       START_TIME::TIMESTAMP_TZ AS START_TIME,
       END_TIME::TIMESTAMP_TZ AS END_TIME,
       AUTO_TARGETING_ENABLED::BOOLEAN AS AUTO_TARGETING_ENABLED,
       TARGETING_SPEC_INTEREST::VARCHAR AS TARGETING_SPEC_INTEREST,
       TARGETING_SPEC_LOCATION::VARCHAR AS TARGETING_SPEC_LOCATION,
       TARGETING_SPEC_AUDIENCE_INCLUDE::VARCHAR AS TARGETING_SPEC_AUDIENCE_INCLUDE,
       TARGETING_SPEC_GENDER::VARCHAR AS TARGETING_SPEC_GENDER,
       TARGETING_SPEC_LOCALE::VARCHAR AS TARGETING_SPEC_LOCALE,
       TARGETING_SPEC_APPTYPE::VARCHAR AS TARGETING_SPEC_APPTYPE,
       TARGETING_SPEC_AGE_BUCKET::VARCHAR AS TARGETING_SPEC_AGE_BUCKET,
       CREATED_TIME::TIMESTAMP_TZ AS CREATED_AT,
       UPDATED_TIME::TIMESTAMP_TZ AS UPDATED_AT,
       -- this is temporary hotfix to avoid data discrepancy - duplicates in entity tables
       ROW_NUMBER() OVER (PARTITION BY ID ORDER BY _FIVETRAN_SYNCED DESC) AS ROW_NUM
FROM "PINTEREST_ADS_1"."AD_GROUP_HISTORY")
WHERE ROW_NUM = 1
;