CREATE OR REPLACE VIEW PINTEREST_VIEWS.ENTITY_KEYWORDS AS
SELECT
    ADVERTISER_ID,
    CAMPAIGN_ID,
    AD_GROUP_ID,
    ID,
    VALUE,
    BID,
    ARCHIVED,
    DELETED,
    EXCLUDE,
    MATCH_TYPE,
    NEW_MATCH_TYPE,
    PARENT_TYPE,
    __PROCESSED_AT
 FROM (
SELECT ADVERTISER_ID::VARCHAR AS ADVERTISER_ID,
       CAMPAIGN_ID::VARCHAR AS CAMPAIGN_ID,
       AD_GROUP_ID::VARCHAR AS AD_GROUP_ID,
       ID::VARCHAR AS ID,
       VALUE::VARCHAR AS VALUE,
       BID::NUMBER(38,0) AS BID,
       ARCHIVED::BOOLEAN AS ARCHIVED,
       DELETED::BOOLEAN AS DELETED,
       EXCLUDE::BOOLEAN AS EXCLUDE,
       MATCH_TYPE::VARCHAR AS MATCH_TYPE,
       NEW_MATCH_TYPE::VARCHAR AS NEW_MATCH_TYPE,
       PARENT_TYPE::VARCHAR AS PARENT_TYPE,
       _FIVETRAN_SYNCED::TIMESTAMP_TZ AS __PROCESSED_AT,
       -- this is temporary hotfix to avoid data discrepancy - duplicates in entity tables
       ROW_NUMBER() OVER (PARTITION BY ID ORDER BY _FIVETRAN_SYNCED DESC) AS ROW_NUM
FROM "PINTEREST_ADS_1"."KEYWORD_HISTORY")
WHERE ROW_NUM = 1
;