CREATE OR REPLACE VIEW "FACEBOOK_VIEWS"."ENTITY_CAMPAIGNS" AS
SELECT

	ID::NUMBER(38,0)						AS CAMPAIGN_ID
	, UPDATED_TIME::TIMESTAMP_TZ(9)			AS UPDATED_TIME
	, ACCOUNT_ID::NUMBER(38,0)				AS ACCOUNT_ID
	, SOURCE_CAMPAIGN_ID::NUMBER(38,0)		AS SOURCE_CAMPAIGN_ID
	, BOOSTED_OBJECT_ID::NUMBER(38,0)		AS BOOSTED_OBJECT_ID
	, BUDGET_REBALANCE_FLAG::BOOLEAN		AS BUDGET_REBALANCE_FLAG
	, BUYING_TYPE::VARCHAR(256)				AS BUYING_TYPE
	, CAN_CREATE_BRAND_LIFT_STUDY::BOOLEAN	AS CAN_CREATE_BRAND_LIFT_STUDY
	, CAN_USE_SPEND_CAP::BOOLEAN			AS CAN_USE_SPEND_CAP
	, CONFIGURED_STATUS::VARCHAR(256)		AS CONFIGURED_STATUS
	, CREATED_TIME::TIMESTAMP_TZ(9)			AS CREATED_TIME
	, EFFECTIVE_STATUS::VARCHAR(256)		AS EFFECTIVE_STATUS
	, NAME::VARCHAR(256)					AS CAMPAIGN_NAME
	, OBJECTIVE::VARCHAR(256)				AS OBJECTIVE
	, SPEND_CAP::NUMBER(38,0)				AS SPEND_CAP
	, START_TIME::TIMESTAMP_TZ(9)			AS START_TIME
	, STATUS::VARCHAR(256)					AS CAMPAIGN_STATUS
	, STOP_TIME::TIMESTAMP_TZ(9)			AS STOP_TIME
	, DAILY_BUDGET::NUMBER(38,0)			AS DAILY_BUDGET
	, _FIVETRAN_SYNCED::TIMESTAMP_TZ(9)		AS _FIVETRAN_SYNCED

FROM
  (
    SELECT
      *,
      ROW_NUMBER() OVER (
        Partition By ID
        ORDER BY
          _FIVETRAN_SYNCED DESC
      ) ___R
    FROM
      "FACEBOOK"."CAMPAIGN_HISTORY"
  )
WHERE ___R = 1
;
