CREATE OR REPLACE VIEW "FACEBOOK_VIEWS"."ENTITY_ADS" AS
SELECT

	ID::NUMBER(38,0)  AS AD_ID
	, UPDATED_TIME::TIMESTAMP_TZ(9)  AS UPDATED_TIME
	, ACCOUNT_ID::NUMBER(38,0)  AS ACCOUNT_ID
	, CAMPAIGN_ID::NUMBER(38,0)  AS CAMPAIGN_ID
	, CREATIVE_ID::NUMBER(38,0)  AS CREATIVE_ID
	, BID_AMOUNT::NUMBER(38,0)  AS BID_AMOUNT
	, BID_TYPE::VARCHAR(256)  AS BID_TYPE
	, CONFIGURED_STATUS::VARCHAR(256)  AS CONFIGURED_STATUS
	, CREATED_TIME::TIMESTAMP_TZ(9)  AS CREATED_TIME
	, EFFECTIVE_STATUS::VARCHAR(256)  AS EFFECTIVE_STATUS
	, LAST_UPDATED_BY_APP_ID::VARCHAR(256)  AS LAST_UPDATED_BY_APP_ID
	, NAME::VARCHAR(256)  AS AD_NAME
	, STATUS::VARCHAR(256)  AS AD_STATUS
	, AD_SET_ID::NUMBER(38,0)  AS AD_SET_ID
	, AD_SOURCE_ID::NUMBER(38,0)  AS AD_SOURCE_ID
	, _FIVETRAN_SYNCED::TIMESTAMP_TZ(9)  AS _FIVETRAN_SYNCED
	, BID_INFO_ACTIONS::NUMBER(38,0)  AS BID_INFO_ACTIONS

FROM
  (
    SELECT
      *,
      ROW_NUMBER() OVER (
        Partition By ID
        ORDER BY
          _FIVETRAN_SYNCED DESC
      ) ___R
    FROM
      "FACEBOOK"."AD_HISTORY"
  )
WHERE ___R = 1
;
