CREATE OR REPLACE VIEW "FACEBOOK_VIEWS"."ENTITY_AD_SETS" AS
SELECT

	ID::VARCHAR  AS AD_SET_ID
	, UPDATED_TIME::TIMESTAMP_TZ(9)  AS UPDATED_TIME
	, CAMPAIGN_ID::VARCHAR  AS CAMPAIGN_ID
	, ACCOUNT_ID::VARCHAR  AS ACCOUNT_ID
	, BID_AMOUNT::NUMBER(38,0)  AS BID_AMOUNT
	, BID_STRATEGY::VARCHAR(256)  AS BID_STRATEGY
	, BILLING_EVENT::VARCHAR(256)  AS BILLING_EVENT
	, BUDGET_REMAINING::NUMBER(38,0)  AS BUDGET_REMAINING
	, CONFIGURED_STATUS::VARCHAR(256)  AS CONFIGURED_STATUS
	, CREATED_TIME::TIMESTAMP_TZ(9)  AS CREATED_TIME
	, DAILY_BUDGET::NUMBER(38,0)  AS DAILY_BUDGET
	, DESTINATION_TYPE::VARCHAR(256)  AS DESTINATION_TYPE
	, EFFECTIVE_STATUS::VARCHAR(256)  AS EFFECTIVE_STATUS
	, END_TIME::TIMESTAMP_TZ(9)  AS END_TIME
	, INSTAGRAM_ACTOR_ID::VARCHAR  AS INSTAGRAM_ACTOR_ID
	, LIFETIME_BUDGET::NUMBER(38,0)  AS LIFETIME_BUDGET
	, LIFETIME_IMPS::NUMBER(38,0)  AS LIFETIME_IMPS
	, NAME::VARCHAR(256)  AS AD_SET_NAME
	, OPTIMIZATION_GOAL::VARCHAR(256)  AS OPTIMIZATION_GOAL
	, RECURRING_BUDGET_SEMANTICS::BOOLEAN  AS RECURRING_BUDGET_SEMANTICS
	, RF_PREDICTION_ID::VARCHAR(256)  AS RF_PREDICTION_ID
	, STATUS::VARCHAR(256)  AS AD_SET_STATUS
	, START_TIME::TIMESTAMP_TZ(9)  AS START_TIME
	, USE_NEW_APP_CLICK::BOOLEAN  AS USE_NEW_APP_CLICK
	, PROMOTED_OBJECT_APPLICATION_ID::VARCHAR(256)  AS PROMOTED_OBJECT_APPLICATION_ID
	, PROMOTED_OBJECT_CUSTOM_EVENT_TYPE::VARCHAR(256)  AS PROMOTED_OBJECT_CUSTOM_EVENT_TYPE
	, PROMOTED_OBJECT_EVENT_ID::VARCHAR  AS PROMOTED_OBJECT_EVENT_ID
	, PROMOTED_OBJECT_OBJECT_STORE_URL::VARCHAR(256)  AS PROMOTED_OBJECT_OBJECT_STORE_URL
	, PROMOTED_OBJECT_OFFER_ID::VARCHAR  AS PROMOTED_OBJECT_OFFER_ID
	, PROMOTED_OBJECT_PAGE_ID::VARCHAR  AS PROMOTED_OBJECT_PAGE_ID
	, PROMOTED_OBJECT_PIXEL_ID::VARCHAR  AS PROMOTED_OBJECT_PIXEL_ID
	, PROMOTED_OBJECT_PLACE_PAGE_SET_ID::VARCHAR  AS PROMOTED_OBJECT_PLACE_PAGE_SET_ID
	, PROMOTED_OBJECT_PRODUCT_CATALOG_ID::VARCHAR  AS PROMOTED_OBJECT_PRODUCT_CATALOG_ID
	, PROMOTED_OBJECT_PRODUCT_SET_ID::VARCHAR  AS PROMOTED_OBJECT_PRODUCT_SET_ID
	, TARGETING_APP_INSTALL_STATE::VARCHAR(256)  AS TARGETING_APP_INSTALL_STATE
	, TARGETING_AGE_MAX::NUMBER(38,0)  AS TARGETING_AGE_MAX
	, TARGETING_AGE_MIN::NUMBER(38,0)  AS TARGETING_AGE_MIN
	, TARGETING_AUDIENCE_NETWORK_POSITIONS::VARIANT  AS TARGETING_AUDIENCE_NETWORK_POSITIONS
	, TARGETING_CONNECTIONS::VARIANT  AS TARGETING_CONNECTIONS
	, TARGETING_DEVICE_PLATFORMS::VARIANT  AS TARGETING_DEVICE_PLATFORMS
	, TARGETING_EFFECTIVE_AUDIENCE_NETWORK_POSITIONS::VARIANT  AS TARGETING_EFFECTIVE_AUDIENCE_NETWORK_POSITIONS
	, TARGETING_EXCLUDED_CONNECTIONS::VARIANT  AS TARGETING_EXCLUDED_CONNECTIONS
	, TARGETING_EXCLUDED_PUBLISHER_CATEGORIES::VARIANT  AS TARGETING_EXCLUDED_PUBLISHER_CATEGORIES
	, TARGETING_EXCLUDED_PUBLISHER_LIST_IDS::VARIANT  AS TARGETING_EXCLUDED_PUBLISHER_LIST_IDS
	, TARGETING_EXCLUDED_USER_DEVICE::VARIANT  AS TARGETING_EXCLUDED_USER_DEVICE
	, TARGETING_FACEBOOK_POSITIONS::VARIANT  AS TARGETING_FACEBOOK_POSITIONS
	, TARGETING_FRIENDS_OF_CONNECTIONS::VARIANT  AS TARGETING_FRIENDS_OF_CONNECTIONS
	, TARGETING_INSTAGRAM_POSITIONS::VARIANT  AS TARGETING_INSTAGRAM_POSITIONS
	, TARGETING_PUBLISHER_PLATFORMS::VARIANT  AS TARGETING_PUBLISHER_PLATFORMS
	, TARGETING_USER_OS::VARIANT  AS TARGETING_USER_OS
	, TARGETING_USER_DEVICE::VARIANT  AS TARGETING_USER_DEVICE
	, TARGETING_WIRELESS_CARRIER::VARIANT  AS TARGETING_WIRELESS_CARRIER
	, TARGETING_EDUCATION_SCHOOLS::VARIANT  AS TARGETING_EDUCATION_SCHOOLS
	, TARGETING_EDUCATION_STATUSES::VARIANT  AS TARGETING_EDUCATION_STATUSES
	, TARGETING_COLLEGE_YEARS::VARIANT  AS TARGETING_COLLEGE_YEARS
	, TARGETING_EDUCATION_MAJORS::VARIANT  AS TARGETING_EDUCATION_MAJORS
	, TARGETING_WORK_EMPLOYERS::VARIANT  AS TARGETING_WORK_EMPLOYERS
	, TARGETING_WORK_POSITIONS::VARIANT  AS TARGETING_WORK_POSITIONS
	, TARGETING_LOCALES::VARIANT  AS TARGETING_LOCALES
	, TARGETING_USER_ADCLUSTERS::VARIANT  AS TARGETING_USER_ADCLUSTERS
	, TARGETING_FLEXIBLE_SPEC::VARIANT  AS TARGETING_FLEXIBLE_SPEC
	, TARGETING_EXCLUSIONS::VARIANT  AS TARGETING_EXCLUSIONS
	, TARGETING_GEO_LOCATIONS_COUNTRIES::VARIANT  AS TARGETING_GEO_LOCATIONS_COUNTRIES
	, TARGETING_GEO_LOCATIONS_LOCATION_TYPES::VARIANT  AS TARGETING_GEO_LOCATIONS_LOCATION_TYPES
	, ADSET_SOURCE_ID::NUMBER(38,0)  AS ADSET_SOURCE_ID
	, _FIVETRAN_SYNCED::TIMESTAMP_TZ(9)  AS _FIVETRAN_SYNCED
	, BID_INFO_ACTIONS::NUMBER(38,0)  AS BID_INFO_ACTIONS

FROM
  (
    SELECT
      *,
      ROW_NUMBER() OVER (
        Partition By ID
        ORDER BY
          _FIVETRAN_SYNCED DESC
      ) ___R
    FROM
      "FACEBOOK"."AD_SET_HISTORY"
  )
WHERE ___R = 1
;
