CREATE OR REPLACE VIEW "FACEBOOK_VIEWS"."ENTITY_CUSTOM_AUDIENCES" AS
SELECT

	ID::VARCHAR     												AS CUSTOM_AUDIENCE_ID
	, UPDATED_TIME::TIMESTAMP_TZ(9)									AS UPDATED_TIME
	, ACCOUNT_ID::VARCHAR   										AS ACCOUNT_ID
	, APPROXIMATE_COUNT::NUMBER(38,0)								AS APPROXIMATE_COUNT
	, DESCRIPTION::VARCHAR(256)										AS DESCRIPTION
	, IS_VALUE_BASED::BOOLEAN										AS IS_VALUE_BASED
	, NAME::VARCHAR(256)											AS CUSTOM_AUDIENCE_NAME
	, OPT_OUT_LINK::VARCHAR(256)									AS OPT_OUT_LINK
	, RETENTION_DAYS::NUMBER(38,0)									AS RETENTION_DAYS
	, RULE::VARCHAR(32768)											AS RULE
	, RULE_AGGREGATION::VARCHAR(256)								AS RULE_AGGREGATION
	, SUBTYPE::VARCHAR(256)											AS SUBTYPE
	, DATA_SOURCE_CREATION_PARAMS::VARCHAR(256)						AS DATA_SOURCE_CREATION_PARAMS
	, DATA_SOURCE_SUB_TYPE::VARCHAR(256)							AS DATA_SOURCE_SUB_TYPE
	, DATA_SOURCE_TYPE::VARCHAR(256)								AS DATA_SOURCE_TYPE
	, DELIVERY_STATUS_CODE::NUMBER(38,0)							AS DELIVERY_STATUS_CODE
	, DELIVERY_STATUS_DESCRIPTION::VARCHAR(256)						AS DELIVERY_STATUS_DESCRIPTION
	, LOOKALIKE_COUNTRY::VARCHAR(256)								AS LOOKALIKE_COUNTRY
	, LOOKALIKE_IS_FINANCIAL_SERVICE::BOOLEAN						AS LOOKALIKE_IS_FINANCIAL_SERVICE
	, LOOKALIKE_RATIO::FLOAT										AS LOOKALIKE_RATIO
	, LOOKALIKE_STARTING_RATIO::FLOAT								AS LOOKALIKE_STARTING_RATIO
	, LOOKALIKE_TYPE::VARCHAR(256)									AS LOOKALIKE_TYPE
	, OPERATION_STATUS_CODE::NUMBER(38,0)							AS OPERATION_STATUS_CODE
	, OPERATION_STATUS_DESCRIPTION::VARCHAR(256)					AS OPERATION_STATUS_DESCRIPTION
	, PERMISSION_FOR_ACTIONS_CAN_EDIT::BOOLEAN						AS PERMISSION_FOR_ACTIONS_CAN_EDIT
	, PERMISSION_FOR_ACTIONS_CAN_SEE_INSIGHT::BOOLEAN				AS PERMISSION_FOR_ACTIONS_CAN_SEE_INSIGHT
	, PERMISSION_FOR_ACTIONS_CAN_SHARE::BOOLEAN						AS PERMISSION_FOR_ACTIONS_CAN_SHARE
	, PERMISSION_FOR_ACTIONS_SUBTYPE_SUPPORTS_LOOKALIKE::BOOLEAN	AS PERMISSION_FOR_ACTIONS_SUBTYPE_SUPPORTS_LOOKALIKE
	, PERMISSION_FOR_ACTIONS_SUPPORTS_RECIPIENT_LOOKALIKE::BOOLEAN	AS PERMISSION_FOR_ACTIONS_SUPPORTS_RECIPIENT_LOOKALIKE
	, CONTENT_UPDATED_TIME::TIMESTAMP_TZ(9)							AS CONTENT_UPDATED_TIME
	, CREATED_TIME::TIMESTAMP_TZ(9)									AS CREATED_TIME
	, _FIVETRAN_SYNCED::TIMESTAMP_TZ(9)								AS _FIVETRAN_SYNCED

FROM
  (
    SELECT
      *,
      ROW_NUMBER() OVER (
        Partition By ID
        ORDER BY
          _FIVETRAN_SYNCED DESC
      ) ___R
    FROM
      "FACEBOOK"."CUSTOM_AUDIENCE_HISTORY"
  )
WHERE ___R = 1
;
