CREATE OR REPLACE VIEW "FACEBOOK_VIEWS"."ENTITY_CREATIVES" AS
SELECT

	ACCOUNT_ID::NUMBER(38,0)						AS ACCOUNT_ID
	, ID::NUMBER(38,0)								AS CREATIVE_ID
	, ACTOR_ID::NUMBER(38,0)						AS ACTOR_ID
	, EFFECTIVE_INSTAGRAM_STORY_ID::NUMBER(38,0)	AS EFFECTIVE_INSTAGRAM_STORY_ID
	, EFFECTIVE_OBJECT_STORY_ID::VARCHAR(256)		AS EFFECTIVE_OBJECT_STORY_ID
	, BODY::VARCHAR(512)							AS BODY
	, IMAGE_FILE::VARCHAR(256)						AS IMAGE_FILE
	, IMAGE_HASH::VARCHAR(256)						AS IMAGE_HASH
	, IMAGE_URL::VARCHAR(512)						AS IMAGE_URL
	, INSTAGRAM_ACTOR_ID::NUMBER(38,0)				AS INSTAGRAM_ACTOR_ID
	, INSTAGRAM_PERMALINK_URL::VARCHAR(256)			AS INSTAGRAM_PERMALINK_URL
	, INSTAGRAM_STORY_ID::NUMBER(38,0)				AS INSTAGRAM_STORY_ID
	, LINK_OG_ID::NUMBER(38,0)						AS LINK_OG_ID
	, LINK_URL::VARCHAR(256)						AS LINK_URL
	, NAME::VARCHAR(256)							AS CREATIVE_NAME
	, OBJECT_ID::NUMBER(38,0)						AS OBJECT_ID
	, OBJECT_STORY_ID::VARCHAR(256)					AS OBJECT_STORY_ID
	, OBJECT_URL::VARCHAR(256)						AS OBJECT_URL
	, STATUS::VARCHAR(256)							AS CREATIVE_STATUS
	, TEMPLATE_URL::VARCHAR(256)					AS TEMPLATE_URL
	, THUMBNAIL_URL::VARCHAR(512)					AS THUMBNAIL_URL
	, TITLE::VARCHAR(256)							AS TITLE
	, USE_PAGE_ACTOR_OVERRIDE::BOOLEAN				AS USE_PAGE_ACTOR_OVERRIDE
	, VIDEO_ID::NUMBER(38,0)						AS VIDEO_ID
	, PRODUCT_SET_ID::NUMBER(38,0)					AS PRODUCT_SET_ID
	, APPLINK_TREATMENT::VARCHAR(256)				AS APPLINK_TREATMENT
	, CALL_TO_ACTION_TYPE::VARCHAR(256)				AS CALL_TO_ACTION_TYPE
	, OBJECT_TYPE::VARCHAR(256)						AS OBJECT_TYPE
	, BRANDED_CONTENT_SPONSOR_PAGE_ID::NUMBER(38,0)	AS BRANDED_CONTENT_SPONSOR_PAGE_ID
	, CAROUSEL_AD_LINK::VARCHAR(256)				AS CAROUSEL_AD_LINK
	, PAGE_LINK::VARCHAR(256)						AS PAGE_LINK
	, TEMPLATE_PAGE_LINK::VARCHAR(256)				AS TEMPLATE_PAGE_LINK
	, LINK_CAPTION::VARCHAR(256)					AS LINK_CAPTION
	, LINK_MESSAGE::VARCHAR(256)					AS LINK_MESSAGE
	, LINK_DESCRIPTION::VARCHAR(256)				AS LINK_DESCRIPTION
	, TEMPLATE_CAPTION::VARCHAR(256)				AS TEMPLATE_CAPTION
	, TEMPLATE_MESSAGE::VARCHAR(256)				AS TEMPLATE_MESSAGE
	, TEMPLATE_DESCRIPTION::VARCHAR(256)			AS TEMPLATE_DESCRIPTION
	, PAGE_MESSAGE::VARCHAR(256)					AS PAGE_MESSAGE
    , _FIVETRAN_ID::VARCHAR(256)					AS _FIVETRAN_ID
	, _FIVETRAN_SYNCED::TIMESTAMP_TZ(9)				AS _FIVETRAN_SYNCED

FROM
  (
    SELECT
      *,
      ROW_NUMBER() OVER (
        Partition By ID
        ORDER BY
          _FIVETRAN_SYNCED DESC
      ) ___R
    FROM
      "FACEBOOK"."CREATIVE_HISTORY"
  )
WHERE ___R = 1
;
