CREATE OR REPLACE VIEW "FACEBOOK_VIEWS"."METRIC_ADS_DAILY_BY_AGE_GENDER" AS
SELECT

    BASE.AD_ID::VARCHAR(256)					AS AD_ID
	, BASE.DATE::DATE							AS DATE
	, BASE.ACCOUNT_ID::NUMBER(38,0)				AS ACCOUNT_ID
	, BASE.ADSET_ID::NUMBER(38,0)				AS ADSET_ID
	, BASE.CAMPAIGN_ID::NUMBER(38,0)			AS CAMPAIGN_ID
    , BASE.AGE::VARCHAR(256)                    AS AGE
    , BASE.GENDER::VARCHAR(256)                 AS GENDER
	, BASE.CLICKS::NUMBER(38,0)					AS CLICKS
	, BASE.IMPRESSIONS::NUMBER(38,0)			AS IMPRESSIONS
	, BASE.SPEND::FLOAT							AS SPEND
    , BASE._FIVETRAN_SYNCED::TIMESTAMP_TZ(9)	AS _FIVETRAN_SYNCED
    
    , VIDEO_30_SEC.VIDEO_30_SEC_WATCHED_ACTIONS__VIDEO_VIEW__VALUE
    , VIDEO_30_SEC.VIDEO_10_SEC_WATCHED_ACTIONS__VIDEO_VIEW__1D_VIEW
    , VIDEO_30_SEC.VIDEO_10_SEC_WATCHED_ACTIONS__VIDEO_VIEW__7D_CLICK
    
    , VIDEO_AVG_TIME.VIDEO_AVG_TIME_WATCHED_ACTIONS__VIDEO_VIEW__VALUE
    , VIDEO_AVG_TIME.VIDEO_AVG_TIME_WATCHED_ACTIONS__VIDEO_VIEW__1D_VIEW
    , VIDEO_AVG_TIME.VIDEO_AVG_TIME_WATCHED_ACTIONS__VIDEO_VIEW__7D_CLICK
    
    , VIDEO_PLAY.VIDEO_PLAY_ACTIONS__VIDEO_VIEW__VALUE
    , VIDEO_PLAY.VIDEO_PLAY_ACTIONS__VIDEO_VIEW__1D_VIEW
    , VIDEO_PLAY.VIDEO_PLAY_ACTIONS__VIDEO_VIEW__7D_CLICK
    
    , VIDEO_P25.VIDEO_P25_WATCHED_ACTIONS__VIDEO_VIEW__VALUE
    , VIDEO_P25.VIDEO_P25_WATCHED_ACTIONS__VIDEO_VIEW__1D_VIEW
    , VIDEO_P25.VIDEO_P25_WATCHED_ACTIONS__VIDEO_VIEW__7D_CLICK
    
    , VIDEO_P50.VIDEO_P50_WATCHED_ACTIONS__VIDEO_VIEW__VALUE
    , VIDEO_P50.VIDEO_P50_WATCHED_ACTIONS__VIDEO_VIEW__1D_VIEW
    , VIDEO_P50.VIDEO_P50_WATCHED_ACTIONS__VIDEO_VIEW__7D_CLICK

    , VIDEO_P75.VIDEO_P75_WATCHED_ACTIONS__VIDEO_VIEW__VALUE
    , VIDEO_P75.VIDEO_P75_WATCHED_ACTIONS__VIDEO_VIEW__1D_VIEW
    , VIDEO_P75.VIDEO_P75_WATCHED_ACTIONS__VIDEO_VIEW__7D_CLICK

    , VIDEO_P95.VIDEO_P95_WATCHED_ACTIONS__VIDEO_VIEW__VALUE
    , VIDEO_P95.VIDEO_P95_WATCHED_ACTIONS__VIDEO_VIEW__1D_VIEW
    , VIDEO_P95.VIDEO_P95_WATCHED_ACTIONS__VIDEO_VIEW__7D_CLICK

    , VIDEO_P100.VIDEO_P100_WATCHED_ACTIONS__VIDEO_VIEW__VALUE
    , VIDEO_P100.VIDEO_P100_WATCHED_ACTIONS__VIDEO_VIEW__1D_VIEW
    , VIDEO_P100.VIDEO_P100_WATCHED_ACTIONS__VIDEO_VIEW__7D_CLICK

FROM (
  
  SELECT *
  FROM "FACEBOOK"."AGE_GENDER"

) AS BASE

LEFT JOIN (

  SELECT AD_ID
    , DATE
    , AGE
    , GENDER
    , VALUE AS VIDEO_30_SEC_WATCHED_ACTIONS__VIDEO_VIEW__VALUE
    , _1_D_VIEW AS VIDEO_10_SEC_WATCHED_ACTIONS__VIDEO_VIEW__1D_VIEW
    , _7_D_CLICK AS VIDEO_10_SEC_WATCHED_ACTIONS__VIDEO_VIEW__7D_CLICK
  FROM "FACEBOOK"."AGE_GENDER_VIDEO_30_SEC_WATCHED_ACTIONS"

) AS VIDEO_30_SEC

ON BASE.DATE = VIDEO_30_SEC.DATE
    AND BASE.AD_ID = VIDEO_30_SEC.AD_ID
    AND BASE.AGE = VIDEO_30_SEC.AGE
    AND BASE.GENDER = VIDEO_30_SEC.GENDER

LEFT JOIN (

  SELECT AD_ID
    , DATE
    , AGE
    , GENDER
    , VALUE AS VIDEO_AVG_TIME_WATCHED_ACTIONS__VIDEO_VIEW__VALUE
    , _1_D_VIEW AS VIDEO_AVG_TIME_WATCHED_ACTIONS__VIDEO_VIEW__1D_VIEW
    , _7_D_CLICK AS VIDEO_AVG_TIME_WATCHED_ACTIONS__VIDEO_VIEW__7D_CLICK
  FROM "FACEBOOK"."AGE_GENDER_VIDEO_AVG_TIME_WATCHED_ACTIONS"

) AS VIDEO_AVG_TIME

ON BASE.DATE = VIDEO_AVG_TIME.DATE
    AND BASE.AD_ID = VIDEO_AVG_TIME.AD_ID
    AND BASE.AGE = VIDEO_AVG_TIME.AGE
    AND BASE.GENDER = VIDEO_AVG_TIME.GENDER

LEFT JOIN (

  SELECT AD_ID
    , DATE
    , AGE
    , GENDER
    , VALUE AS VIDEO_PLAY_ACTIONS__VIDEO_VIEW__VALUE
    , _1_D_VIEW AS VIDEO_PLAY_ACTIONS__VIDEO_VIEW__1D_VIEW
    , _7_D_CLICK AS VIDEO_PLAY_ACTIONS__VIDEO_VIEW__7D_CLICK
  FROM "FACEBOOK"."AGE_GENDER_VIDEO_PLAY_ACTIONS"

) AS VIDEO_PLAY

ON BASE.DATE = VIDEO_PLAY.DATE
    AND BASE.AD_ID = VIDEO_PLAY.AD_ID
    AND BASE.AGE = VIDEO_PLAY.AGE
    AND BASE.GENDER = VIDEO_PLAY.GENDER

LEFT JOIN (

  SELECT AD_ID
    , DATE
    , AGE
    , GENDER
    , VALUE AS VIDEO_P25_WATCHED_ACTIONS__VIDEO_VIEW__VALUE
    , _1_D_VIEW AS VIDEO_P25_WATCHED_ACTIONS__VIDEO_VIEW__1D_VIEW
    , _7_D_CLICK AS VIDEO_P25_WATCHED_ACTIONS__VIDEO_VIEW__7D_CLICK
  FROM "FACEBOOK"."AGE_GENDER_VIDEO_P_25_WATCHED_ACTIONS"

) AS VIDEO_P25

ON BASE.DATE = VIDEO_P25.DATE
    AND BASE.AD_ID = VIDEO_P25.AD_ID
    AND BASE.AGE = VIDEO_P25.AGE
    AND BASE.GENDER = VIDEO_P25.GENDER

LEFT JOIN (

  SELECT AD_ID
    , DATE
    , AGE
    , GENDER
    , VALUE AS VIDEO_P50_WATCHED_ACTIONS__VIDEO_VIEW__VALUE
    , _1_D_VIEW AS VIDEO_P50_WATCHED_ACTIONS__VIDEO_VIEW__1D_VIEW
    , _7_D_CLICK AS VIDEO_P50_WATCHED_ACTIONS__VIDEO_VIEW__7D_CLICK
  FROM "FACEBOOK"."AGE_GENDER_VIDEO_P_50_WATCHED_ACTIONS"

) AS VIDEO_P50

ON BASE.DATE = VIDEO_P50.DATE
    AND BASE.AD_ID = VIDEO_P50.AD_ID
    AND BASE.AGE = VIDEO_P50.AGE
    AND BASE.GENDER = VIDEO_P50.GENDER

LEFT JOIN (

  SELECT AD_ID
    , DATE
    , AGE
    , GENDER
    , VALUE AS VIDEO_P75_WATCHED_ACTIONS__VIDEO_VIEW__VALUE
    , _1_D_VIEW AS VIDEO_P75_WATCHED_ACTIONS__VIDEO_VIEW__1D_VIEW
    , _7_D_CLICK AS VIDEO_P75_WATCHED_ACTIONS__VIDEO_VIEW__7D_CLICK
  FROM "FACEBOOK"."AGE_GENDER_VIDEO_P_75_WATCHED_ACTIONS"

) AS VIDEO_P75

ON BASE.DATE = VIDEO_P75.DATE
    AND BASE.AD_ID = VIDEO_P75.AD_ID
    AND BASE.AGE = VIDEO_P75.AGE
    AND BASE.GENDER = VIDEO_P75.GENDER

LEFT JOIN (

  SELECT AD_ID
    , DATE
    , AGE
    , GENDER
    , VALUE AS VIDEO_P95_WATCHED_ACTIONS__VIDEO_VIEW__VALUE
    , _1_D_VIEW AS VIDEO_P95_WATCHED_ACTIONS__VIDEO_VIEW__1D_VIEW
    , _7_D_CLICK AS VIDEO_P95_WATCHED_ACTIONS__VIDEO_VIEW__7D_CLICK
  FROM "FACEBOOK"."AGE_GENDER_VIDEO_P_95_WATCHED_ACTIONS"

) AS VIDEO_P95

ON BASE.DATE = VIDEO_P95.DATE
    AND BASE.AD_ID = VIDEO_P95.AD_ID
    AND BASE.AGE = VIDEO_P95.AGE
    AND BASE.GENDER = VIDEO_P95.GENDER
    
LEFT JOIN (

  SELECT AD_ID
    , DATE
    , AGE
    , GENDER
    , VALUE AS VIDEO_P100_WATCHED_ACTIONS__VIDEO_VIEW__VALUE
    , _1_D_VIEW AS VIDEO_P100_WATCHED_ACTIONS__VIDEO_VIEW__1D_VIEW
    , _7_D_CLICK AS VIDEO_P100_WATCHED_ACTIONS__VIDEO_VIEW__7D_CLICK
  FROM "FACEBOOK"."AGE_GENDER_VIDEO_P_100_WATCHED_ACTIONS"

) AS VIDEO_P100

ON BASE.DATE = VIDEO_P100.DATE
    AND BASE.AD_ID = VIDEO_P100.AD_ID
    AND BASE.AGE = VIDEO_P100.AGE
    AND BASE.GENDER = VIDEO_P100.GENDER

;