CREATE OR REPLACE VIEW "FACEBOOK_VIEWS"."METRIC_ADS_DAILY_ACTION_VALUES_REGION" AS
SELECT 

	AD_ID::VARCHAR(256)					    AS AD_ID
	, DATE::DATE							AS DATE
    , REGION::VARCHAR(256)                  AS REGION
	, INDEX::NUMBER(38,0)					AS INDEX
	, ACTION_TYPE::VARCHAR(256)				AS ACTIONS
	, VALUE::FLOAT							AS ACTION_VALUES_VALUE
	, _1_D_VIEW::NUMBER(38,0)				AS ACTION_VALUES_1D_VIEW
	, _FIVETRAN_SYNCED::TIMESTAMP_TZ(9)		AS _FIVETRAN_SYNCED
	, _7_D_CLICK::NUMBER(38,0)				AS ACTION_VALUES_7D_CLICK
    
FROM "FACEBOOK"."REGION_ACTION_VALUES"
;