CREATE OR REPLACE VIEW "SNAPCHAT_VIEWS"."ENTITY_FUNDING_SOURCES" AS

SELECT 

      FUNDING_SOURCE_ID
      , UPDATED_AT
      , ORGANIZATION_ID
      , CREATED_AT
      , START_DATE
      , END_DATE
      , VALUE_MICRO
      , BUDGET_SPENT_MICRO
      , TOTAL_BUDGET_MICRO
      , AVAILABLE_CREDIT_MICRO
      , DAILY_SPEND_LIMIT_MICRO
      , EXPIRATION_MONTH
      , EXPIRATION_YEAR
      , STATUS
      , CURRENCY
      , DAILY_SPEND_LIMIT_CURRENCY
      , CARD_TYPE
      , FUNDING_SOURCE_NAME
      , EMAIL
      , FUNDING_SOURCE_TYPE
      , LAST_4_DIGITS_OF_CARD

FROM (

  SELECT 
      ID::VARCHAR(256)                              AS FUNDING_SOURCE_ID
      , UPDATED_AT::TIMESTAMP_TZ(9)                 AS UPDATED_AT
      , ORGANIZATION_ID::VARCHAR(256)               AS ORGANIZATION_ID
      , CREATED_AT::TIMESTAMP_TZ(9)                 AS CREATED_AT
      , START_DATE::DATE                            AS START_DATE
      , END_DATE::DATE                              AS END_DATE
      , VALUE_MICRO::NUMBER(38,0)                   AS VALUE_MICRO
      , BUDGET_SPENT_MICRO::NUMBER(38,0)            AS BUDGET_SPENT_MICRO
      , TOTAL_BUDGET_MICRO::NUMBER(38,0)            AS TOTAL_BUDGET_MICRO
      , AVAILABLE_CREDIT_MICRO::NUMBER(38,0)        AS AVAILABLE_CREDIT_MICRO
      , DAILY_SPEND_LIMIT_MICRO::NUMBER(38,0)       AS DAILY_SPEND_LIMIT_MICRO
      , EXPIRATION_MONTH::NUMBER(38,0)              AS EXPIRATION_MONTH
      , EXPIRATION_YEAR::NUMBER(38,0)               AS EXPIRATION_YEAR
      , STATUS::VARCHAR(256)                        AS STATUS
      , CURRENCY::VARCHAR(256)                      AS CURRENCY
      , DAILY_SPEND_LIMIT_CURRENCY::VARCHAR(256)    AS DAILY_SPEND_LIMIT_CURRENCY
      , CARD_TYPE::VARCHAR(256)                     AS CARD_TYPE
      , NAME::VARCHAR(256)                          AS FUNDING_SOURCE_NAME
      , EMAIL::VARCHAR(256)                         AS EMAIL
      , TYPE::VARCHAR(256)                          AS FUNDING_SOURCE_TYPE
      , LAST_4_DIGITS_OF_CARD::NUMBER(38,0)         AS LAST_4_DIGITS_OF_CARD
      , _FIVETRAN_SYNCED::TIMESTAMP_TZ(9)
      , ROW_NUMBER() OVER (PARTITION BY ID ORDER BY _FIVETRAN_SYNCED DESC) AS ROW_NUM
  FROM "SNAPCHAT_ADS"."FUNDING_SOURCE_HISTORY"

)
WHERE ROW_NUM = 1
;