CREATE OR REPLACE VIEW "SNAPCHAT_VIEWS"."ENTITY_AD_SQUADS" AS

SELECT 
    AD_SQUAD_ID
    , CAMPAIGN_ID
    , BILLING_EVENT
    , AD_SQUAD_NAME
    , OPTIMIZATION_GOAL
    , PLACEMENT
    , STATUS
    , AD_SQUAD_TYPE
    , START_TIME
    , END_TIME
    , TARGETING_REGULATED_CONTENT
    , AUDIENCE_SIZE_MINIMUM
    , AUDIENCE_SIZE_MAXIMUM
    , BID_ESTIMATE_MINIMUM
    , BID_ESTIMATE_MAXIMUM
    , BID_MICRO
    , AUTO_BID
    , DAILY_BUDGET_MICRO
    , LIFETIME_BUDGET_MICRO
    , LIFETIME_SPEND_MICRO
    , CREATED_AT
    , UPDATED_AT
FROM (

  SELECT 
    ID::VARCHAR(256)                        AS AD_SQUAD_ID
    , CAMPAIGN_ID::VARCHAR(256)             AS CAMPAIGN_ID
    , BILLING_EVENT::VARCHAR(256)           AS BILLING_EVENT
    , NAME::VARCHAR(256)                    AS AD_SQUAD_NAME
    , OPTIMIZATION_GOAL::VARCHAR(256)       AS OPTIMIZATION_GOAL
    , PLACEMENT::VARCHAR(256)               AS PLACEMENT
    , STATUS::VARCHAR(256)                  AS STATUS
    , TYPE::VARCHAR(256)                    AS AD_SQUAD_TYPE
    , START_TIME::TIMESTAMP_TZ(9)           AS START_TIME
    , END_TIME::TIMESTAMP_TZ(9)             AS END_TIME
    , TARGETING_REGULATED_CONTENT::BOOLEAN  AS TARGETING_REGULATED_CONTENT
    , AUTO_BID::BOOLEAN                     AS AUTO_BID
    , AUDIENCE_SIZE_MINIMUM::NUMBER(38,0)   AS AUDIENCE_SIZE_MINIMUM
    , AUDIENCE_SIZE_MAXIMUM::NUMBER(38,0)   AS AUDIENCE_SIZE_MAXIMUM
    , BID_ESTIMATE_MAXIMUM::NUMBER(38,0)    AS BID_ESTIMATE_MAXIMUM
    , BID_ESTIMATE_MINIMUM::NUMBER(38,0)    AS BID_ESTIMATE_MINIMUM
    , BID_MICRO::NUMBER(38,0)               AS BID_MICRO
    , DAILY_BUDGET_MICRO::NUMBER(38,0)      AS DAILY_BUDGET_MICRO
    , LIFETIME_BUDGET_MICRO::NUMBER(38,0)   AS LIFETIME_BUDGET_MICRO
    , LIFETIME_SPEND_MICRO::NUMBER(38,0)    AS LIFETIME_SPEND_MICRO
    , CREATED_AT::TIMESTAMP_TZ(9)           AS CREATED_AT
    , UPDATED_AT::TIMESTAMP_TZ(9)           AS UPDATED_AT
    , _FIVETRAN_SYNCED::TIMESTAMP_TZ(9)
    , ROW_NUMBER() OVER (PARTITION BY ID ORDER BY _FIVETRAN_SYNCED DESC) AS ROW_NUM
  FROM "SNAPCHAT_ADS"."AD_SQUAD_HISTORY"

)
WHERE ROW_NUM = 1
;