CREATE OR REPLACE VIEW "SNAPCHAT_VIEWS"."ENTITY_ADS" AS

SELECT 
    ID
    , AD_SQUAD_ID
    , CREATIVE_ID
    , CREATED_AT
    , UPDATED_AT
    , NAME
    , REVIEW_STATUS
    , STATUS
    , TYPE
    , REVIEW_STATUS_REASONS
FROM (

  SELECT 
    ID::VARCHAR(256)                        AS ID
    , AD_SQUAD_ID::VARCHAR(256)             AS AD_SQUAD_ID
    , CREATIVE_ID::VARCHAR(256)             AS CREATIVE_ID
    , NAME::VARCHAR(256)                    AS NAME
    , REVIEW_STATUS::VARCHAR(256)           AS REVIEW_STATUS
    , REVIEW_STATUS_REASON::VARCHAR(256)    AS REVIEW_STATUS_REASONS
    , STATUS::VARCHAR(256)                  AS STATUS
    , TYPE::VARCHAR(256)                    AS TYPE
    , CREATED_AT::TIMESTAMP_TZ(9)           AS CREATED_AT
    , UPDATED_AT::TIMESTAMP_TZ(9)           AS UPDATED_AT
    , _FIVETRAN_SYNCED::TIMESTAMP_TZ(9)
    , ROW_NUMBER() OVER (PARTITION BY ID ORDER BY _FIVETRAN_SYNCED DESC) AS ROW_NUM
  FROM "SNAPCHAT_ADS"."AD_HISTORY"

)
WHERE ROW_NUM = 1
;