CREATE OR REPLACE VIEW "SNAPCHAT_VIEWS"."ENTITY_CAMPAIGNS" AS

SELECT 

    CAMPAIGN_ID
    , AD_ACCOUNT_ID
    , CAMPAIGN_NAME
    , OBJECTIVE
    , STATUS
    , DAILY_BUDGET_MICRO
    , LIFETIME_SPEND_CAP_MICRO
    , MEASUREMENT_SPEC_ANDROID_APP_URL
    , MEASUREMENT_SPEC_IOS_APP_ID
    , START_TIME
    , END_TIME
    , CREATED_AT
    , UPDATED_AT

FROM (

  SELECT 
      ID::VARCHAR(256)                                  AS CAMPAIGN_ID
      , UPDATED_AT::TIMESTAMP_TZ(9)                     AS UPDATED_AT
      , AD_ACCOUNT_ID::VARCHAR(256)                     AS AD_ACCOUNT_ID
      , NAME::VARCHAR(256)                              AS CAMPAIGN_NAME
      , STATUS::VARCHAR(256)                            AS STATUS
      , DAILY_BUDGET_MICRO::NUMBER(38,0)                AS DAILY_BUDGET_MICRO
      , LIFETIME_SPEND_CAP_MICRO::NUMBER(38,0)          AS LIFETIME_SPEND_CAP_MICRO
      , CREATED_AT::TIMESTAMP_TZ(9)                     AS CREATED_AT
      , END_TIME::TIMESTAMP_TZ(9)                       AS END_TIME
      , START_TIME::TIMESTAMP_TZ(9)                     AS START_TIME
      , OBJECTIVE::VARCHAR(256)                         AS OBJECTIVE
      , MEASUREMENT_SPEC_ANDROID_APP_URL::VARCHAR(256)  AS MEASUREMENT_SPEC_ANDROID_APP_URL
      , MEASUREMENT_SPEC_IOS_APP_ID::NUMBER(38,0)       AS MEASUREMENT_SPEC_IOS_APP_ID
      , _FIVETRAN_SYNCED::TIMESTAMP_TZ(9)
      , ROW_NUMBER() OVER (PARTITION BY ID ORDER BY _FIVETRAN_SYNCED DESC) AS ROW_NUM
  FROM "SNAPCHAT_ADS"."CAMPAIGN_HISTORY"

)
WHERE ROW_NUM = 1
;