CREATE OR REPLACE VIEW "SNAPCHAT_VIEWS"."METRIC_AD_SQUADS_HOURLY" AS
SELECT 

  AD_SQUAD_ID::VARCHAR(256)                                   AS AD_SQUAD_ID
  , DATE::TIMESTAMP_TZ(9)                               AS DATE
  , IMPRESSIONS::NUMBER(38,0)                           AS IMPRESSIONS
  , SWIPES::NUMBER(38,0)                                AS SWIPES
  , VIEW_TIME_MILLIS::NUMBER(38,0)                      AS VIEW_TIME_MILLIS
  , SCREEN_TIME_MILLIS::NUMBER(38,0)                    AS SCREEN_TIME_MILLIS
  , QUARTILE_1::NUMBER(38,0)                            AS QUARTILE_1
  , QUARTILE_2::NUMBER(38,0)                            AS QUARTILE_2
  , QUARTILE_3::NUMBER(38,0)                            AS QUARTILE_3
  , VIEW_COMPLETION::NUMBER(38,0)                       AS VIEW_COMPLETION
  , SPEND::NUMBER(38,0)                                 AS SPEND
  , VIDEO_VIEWS::NUMBER(38,0)                           AS VIDEO_VIEWS
  , ANDROID_INSTALLS::NUMBER(38,0)                      AS ANDROID_INSTALLS
  , ATTACHMENT_AVG_VIEW_TIME_MILLIS::NUMBER(38,0)       AS ATTACHMENT_AVG_VIEW_TIME_MILLIS
  , ATTACHMENT_FREQUENCY::NUMBER(38,0)                  AS ATTACHMENT_FREQUENCY
  , ATTACHMENT_QUARTILE_1::NUMBER(38,0)                 AS ATTACHMENT_QUARTILE_1
  , ATTACHMENT_QUARTILE_2::NUMBER(38,0)                 AS ATTACHMENT_QUARTILE_2
  , ATTACHMENT_QUARTILE_3::NUMBER(38,0)                 AS ATTACHMENT_QUARTILE_3
  , ATTACHMENT_TOTAL_VIEW_TIME_MILLIS::NUMBER(38,0)     AS ATTACHMENT_TOTAL_VIEW_TIME_MILLIS
  , ATTACHMENT_UNIQUES::NUMBER(38,0)                    AS ATTACHMENT_UNIQUES
  , ATTACHMENT_VIEW_COMPLETION::NUMBER(38,0)            AS ATTACHMENT_VIEW_COMPLETION
  , AVG_VIEW_TIME_MILLIS::NUMBER(38,0)                  AS AVG_VIEW_TIME_MILLIS
  , AVG_SCREEN_TIME_MILLIS::NUMBER(38,0)                AS AVG_SCREEN_TIME_MILLIS
  , FREQUENCY::NUMBER(38,0)                             AS FREQUENCY
  , IOS_INSTALLS::NUMBER(38,0)                          AS IOS_INSTALLS
  , TOTAL_INSTALLS::NUMBER(38,0)                        AS TOTAL_INSTALLS
  , SWIPE_UP_PERCENT::NUMBER(38,0)                      AS SWIPE_UP_PERCENT
  , UNIQUES::NUMBER(38,0)                               AS UNIQUES
  , STORY_OPENS::NUMBER(38,0)                           AS STORY_OPENS
  , SHARES::NUMBER(38,0)                                AS SHARES
  , SAVES::NUMBER(38,0)                                 AS SAVES
  , STORY_COMPLETES::NUMBER(38,0)                       AS STORY_COMPLETES
  , CONVERSION_PURCHASES::NUMBER(38,0)                  AS CONVERSION_PURCHASES
  , CONVERSION_PURCHASES_VALUE::NUMBER(38,0)            AS CONVERSION_PURCHASES_VALUE
  , CONVERSION_SAVE::NUMBER(38,0)                       AS CONVERSION_SAVE
  , CONVERSION_START_CHECKOUT::NUMBER(38,0)             AS CONVERSION_START_CHECKOUT
  , CONVERSION_ADD_CART::NUMBER(38,0)                   AS CONVERSION_ADD_CART
  , CONVERSION_VIEW_CONTENT::NUMBER(38,0)               AS CONVERSION_VIEW_CONTENT
  , CONVERSION_ADD_BILLING::NUMBER(38,0)                AS CONVERSION_ADD_BILLING
  , CONVERSION_SIGN_UPS::NUMBER(38,0)                   AS CONVERSION_SIGN_UPS
  , CONVERSION_SEARCHES::NUMBER(38,0)                   AS CONVERSION_SEARCHES
  , CONVERSION_LEVEL_COMPLETES::NUMBER(38,0)            AS CONVERSION_LEVEL_COMPLETES
  , CONVERSION_APP_OPENS::NUMBER(38,0)                  AS CONVERSION_APP_OPENS
  , CONVERSION_PAGE_VIEWS::NUMBER(38,0)                 AS CONVERSION_PAGE_VIEWS
  , _FIVETRAN_SYNCED::TIMESTAMP_TZ(9)                   AS _FIVETRAN_SYNCED

FROM "SNAPCHAT_ADS"."AD_SQUAD_HOURLY_REPORT"
;