CREATE OR REPLACE VIEW "BING_ADS_VIEWS"."ENTITY_AD_GROUPS" AS
SELECT
  DT.ID,
  DT.MODIFIED_TIME,
  DT.LANGUAGE,
  DT.STATUS,
  DT.CAMPAIGN_ID,
  DT.NAME,
  DT.AD_ROTATION,
  DT.BID_ADJUSTMENT,
  DT.BID_BOOST_VALUE,
  DT.BID_OPTION,
  DT.BID_STRATEGY_TYPE,
  DT.CPC_BID,
  DT.INHERITED_BID_STRATEGY_TYPE,
  DT.MAXIMUM_BID,
  DT.NETWORK_DISTRIBUTION,
  DT.PRIVACY_STATUS,
  DT.TARGET_SETTING,
  DT.END_DATE,
  DT.START_DATE,
  DT.TRACKING_TEMPLATE
FROM
  (
    SELECT
      *,
      ROW_NUMBER() OVER (
        Partition By ID
        ORDER BY
          MODIFIED_TIME DESC
      ) ___R
    FROM
      "BING_ADS"."AD_GROUP_HISTORY"
  ) DT
WHERE
  DT.___R = 1;
