CREATE OR REPLACE VIEW "BING_ADS_VIEWS"."ENTITY_KEYWORDS" AS
SELECT
  DT.ID,
  DT.MODIFIED_TIME,
  DT.BID,
  DT.LANGUAGE,
  DT.PARAM_1,
  DT.PARAM_2,
  DT.PARAM_3,
  DT.STATUS,
  DT.AD_GROUP_ID,
  DT.NAME,
  DT.BID_STRATEGY_TYPE,
  DT.DESTINATION_URL,
  DT.EDITORIAL_APPEAL_STATUS,
  DT.EDITORIAL_LOCATION,
  DT.EDITORIAL_REASON_CODE,
  DT.EDITORIAL_STATUS,
  DT.EDITORIAL_TERM,
  DT.FINAL_URL,
  DT.INHERITED_BID_STRATEGY_TYPE,
  DT.MATCH_TYPE,
  DT.MOBILE_FINAL_URL,
  DT.TRACKING_TEMPLATE
FROM
  (
    SELECT
      *,
      ROW_NUMBER() OVER (
        Partition By ID
        ORDER BY
          MODIFIED_TIME DESC
      ) ___R
    FROM
      "BING_ADS"."KEYWORD_HISTORY"
  ) DT
WHERE
  DT.___R = 1;
