CREATE OR REPLACE VIEW "BING_ADS_VIEWS"."ENTITY_ADS" AS
SELECT
  DT.ID,
  DT.MODIFIED_TIME,
  DT.DOMAIN,
  DT.TEXT,
  DT.TITLE,
  DT.STATUS,
  DT.TYPE,
  DT.AD_GROUP_ID,
  DT.AD_FORMAT_PREFERENCE,
  DT.BUSINESS_NAME,
  DT.CALL_TO_ACTION,
  DT.EDITORIAL_APPEAL_STATUS,
  DT.EDITORIAL_LOCATION,
  DT.EDITORIAL_REASON_CODE,
  DT.EDITORIAL_STATUS,
  DT.EDITORIAL_TERM,
  DT.DISPLAY_URL,
  DT.FINAL_URL,
  DT.MOBILE_FINAL_URL,
  DT.PATH_1,
  DT.PATH_2,
  DT.APP_ID,
  DT.APP_PLATFORM,
  DT.DEVICE_PREFERENCE,
  DT.TITLE_PART_1,
  DT.TITLE_PART_2,
  DT.HEAD_LINE,
  DT.LONG_HEAD_LINE,
  DT.LANDSCAPE_IMAGE_MEDIA_ID,
  DT.LANDSCAPE_LOGO_MEDIA_ID,
  DT.SQUARE_IMAGE_MEDIA_ID,
  DT.SQUARE_LOGO_MEDIA_ID,
  DT.TRACKING_TEMPLATE
FROM
  (
    SELECT
      *,
      ROW_NUMBER() OVER (
        Partition By ID
        ORDER BY
          MODIFIED_TIME DESC
      ) ___R
    FROM
      "BING_ADS"."AD_HISTORY"
  ) DT
WHERE
  DT.___R = 1;
