CREATE OR REPLACE VIEW "LINKEDIN_VIEWS"."ENTITY_CREATIVES" AS 

SELECT
    ID
    , TYPE
    , REFERENCE
    , STATUS
    , REVIEW_STATUS
    , VERSION_TAG
    , CALL_TO_ACTION_LABEL_TYPE
    , CALL_TO_ACTION_TARGET
    , CLICK_URI
    , TEXT_AD_TEXT
    , TEXT_AD_TITLE
    , SPONSORED_UPDATE_ACTIVITY
    , SPONSORED_UPDATE_DIRECT_SPONSORED_CONTENT
    , SPONSORED_UPDATE_SHARE
    , SPONSORED_IN_MAIL_CONTENT
    , SPONSORED_VIDEO_MEDIA_ASSET
    , SPONSORED_VIDEO_USER_GENERATED_CONTENT_POST
    , SPONSORED_UPDATE_CAROUSEL_ACTIVITY
    , SPONSORED_UPDATE_CAROUSEL_DIRECT_SPONSORED_CONTENT
    , SPONSORED_UPDATE_CAROUSEL_SHARE
    , FOLLOW_COMPANY_CALL_TO_ACTION
    , FOLLOW_COMPANY_ORGANIZATION_LOGO
    , FOLLOW_COMPANY_ORGANIZATION_NAME
    , SPOTLIGHT_CALL_TO_ACTION
    , SPOTLIGHT_CUSTOM_BACKGROUND
    , SPOTLIGHT_DESCRIPTION
    , SPOTLIGHT_FORUM_NAME
    , SPOTLIGHT_HEADLINE
    , SPOTLIGHT_LOGO
    , SPOTLIGHT_SHOW_MEMBER_PROFILE_PHOTO
    , JOBS_COMPANY_NAME
    , JOBS_LOGO
    , JOBS_ORGANIZATION
    , CAMPAIGN_ID
    , PLATFORM_CREATED_AT
    , PLATFORM_UPDATED_AT
    , PROCESSED_AT

FROM (

  SELECT
    ID::VARCHAR                                                         AS ID
    , TYPE::VARCHAR                                                     AS TYPE
    , REFERENCE::VARCHAR                                                AS REFERENCE
    , STATUS::VARCHAR                                                   AS STATUS
    , REVIEW_STATUS::VARCHAR                                            AS REVIEW_STATUS
    , VERSION_TAG::VARCHAR                                              AS VERSION_TAG
    , CALL_TO_ACTION_LABEL_TYPE::VARCHAR                                AS CALL_TO_ACTION_LABEL_TYPE
    , CALL_TO_ACTION_TARGET::VARCHAR                                    AS CALL_TO_ACTION_TARGET
    , CLICK_URI::VARCHAR                                                AS CLICK_URI
    , TEXT_AD_TEXT::VARCHAR                                             AS TEXT_AD_TEXT
    , TEXT_AD_TITLE::VARCHAR                                            AS TEXT_AD_TITLE
    , SPONSORED_UPDATE_ACTIVITY::VARCHAR                                AS SPONSORED_UPDATE_ACTIVITY
    , SPONSORED_UPDATE_DIRECT_SPONSORED_CONTENT::BOOLEAN                AS SPONSORED_UPDATE_DIRECT_SPONSORED_CONTENT
    , SPONSORED_UPDATE_SHARE::VARCHAR                                   AS SPONSORED_UPDATE_SHARE
    , SPONSORED_IN_MAIL_CONTENT::VARCHAR                                AS SPONSORED_IN_MAIL_CONTENT
    , SPONSORED_VIDEO_MEDIA_ASSET::VARCHAR                              AS SPONSORED_VIDEO_MEDIA_ASSET
    , SPONSORED_VIDEO_USER_GENERATED_CONTENT_POST::VARCHAR              AS SPONSORED_VIDEO_USER_GENERATED_CONTENT_POST
    , SPONSORED_UPDATE_CAROUSEL_ACTIVITY::VARCHAR                       AS SPONSORED_UPDATE_CAROUSEL_ACTIVITY
    , SPONSORED_UPDATE_CAROUSEL_DIRECT_SPONSORED_CONTENT::BOOLEAN       AS SPONSORED_UPDATE_CAROUSEL_DIRECT_SPONSORED_CONTENT
    , SPONSORED_UPDATE_CAROUSEL_SHARE::VARCHAR                          AS SPONSORED_UPDATE_CAROUSEL_SHARE
    , FOLLOW_COMPANY_CALL_TO_ACTION::VARCHAR                            AS FOLLOW_COMPANY_CALL_TO_ACTION
    , FOLLOW_COMPANY_ORGANIZATION_LOGO::VARCHAR                         AS FOLLOW_COMPANY_ORGANIZATION_LOGO
    , FOLLOW_COMPANY_ORGANIZATION_NAME::VARCHAR                         AS FOLLOW_COMPANY_ORGANIZATION_NAME
    , SPOTLIGHT_CALL_TO_ACTION::VARCHAR                                 AS SPOTLIGHT_CALL_TO_ACTION
    , SPOTLIGHT_CUSTOM_BACKGROUND::VARCHAR                              AS SPOTLIGHT_CUSTOM_BACKGROUND
    , SPOTLIGHT_DESCRIPTION::VARCHAR                                    AS SPOTLIGHT_DESCRIPTION
    , SPOTLIGHT_FORUM_NAME::VARCHAR                                     AS SPOTLIGHT_FORUM_NAME
    , SPOTLIGHT_HEADLINE::VARCHAR                                       AS SPOTLIGHT_HEADLINE
    , SPOTLIGHT_LOGO::VARCHAR                                           AS SPOTLIGHT_LOGO
    , SPOTLIGHT_SHOW_MEMBER_PROFILE_PHOTO::BOOLEAN                      AS SPOTLIGHT_SHOW_MEMBER_PROFILE_PHOTO
    , JOBS_COMPANY_NAME::VARCHAR                                        AS JOBS_COMPANY_NAME
    , JOBS_LOGO::VARCHAR                                                AS JOBS_LOGO
    , JOBS_ORGANIZATION::VARCHAR                                        AS JOBS_ORGANIZATION
    , CAMPAIGN_ID::VARCHAR                                              AS CAMPAIGN_ID
    , CREATED_TIME::TIMESTAMP_TZ                                        AS PLATFORM_CREATED_AT
    , LAST_MODIFIED_TIME::TIMESTAMP_TZ                                  AS PLATFORM_UPDATED_AT
    , _FIVETRAN_SYNCED::TIMESTAMP_TZ                                    AS PROCESSED_AT
    , ROW_NUMBER() OVER (PARTITION BY ID ORDER BY _FIVETRAN_SYNCED DESC) AS ROW_NUM
  FROM "LINKEDIN_ADS"."CREATIVE_HISTORY"

)
WHERE ROW_NUM = 1
;