CREATE OR REPLACE VIEW "LINKEDIN_VIEWS"."ENTITY_CAMPAIGNS" AS 

SELECT

    ID
    , NAME
    , TYPE
    , OBJECTIVE_TYPE
    , ASSOCIATED_ENTITY
    , OPTIMIZATION_TARGET_TYPE
    , COST_TYPE
    , CREATIVE_SELECTION
    , OFFSITE_DELIVERY_ENABLED
    , AUDIENCE_EXPANSION_ENABLED
    , STATUS
    , FORMAT
    , LOCALE_COUNTRY
    , LOCALE_LANGUAGE
    , RUN_SCHEDULE_START
    , RUN_SCHEDULE_END
    , VERSION_TAG
    , DAILY_BUDGET_AMOUNT
    , DAILY_BUDGET_CURRENCY_CODE
    , UNIT_COST_AMOUNT
    , UNIT_COST_CURRENCY_CODE
    , CAMPAIGN_GROUP_ID
    , ACCOUNT_ID
    , PLATFORM_CREATED_AT
    , PLATFORM_UPDATED_AT
    , PROCESSED_AT

FROM (

  SELECT
    ID::VARCHAR                                 AS ID
    , NAME::VARCHAR                             AS NAME
    , TYPE::VARCHAR                             AS TYPE
    , OBJECTIVE_TYPE::VARCHAR                   AS OBJECTIVE_TYPE
    , ASSOCIATED_ENTITY::VARCHAR                AS ASSOCIATED_ENTITY
    , OPTIMIZATION_TARGET_TYPE::VARCHAR         AS OPTIMIZATION_TARGET_TYPE
    , COST_TYPE::VARCHAR                        AS COST_TYPE
    , CREATIVE_SELECTION::VARCHAR               AS CREATIVE_SELECTION
    , OFFSITE_DELIVERY_ENABLED::BOOLEAN         AS OFFSITE_DELIVERY_ENABLED
    , AUDIENCE_EXPANSION_ENABLED::BOOLEAN       AS AUDIENCE_EXPANSION_ENABLED
    , STATUS::VARCHAR                           AS STATUS
    , FORMAT::VARCHAR                           AS FORMAT
    , LOCALE_COUNTRY::VARCHAR                   AS LOCALE_COUNTRY
    , LOCALE_LANGUAGE::VARCHAR                  AS LOCALE_LANGUAGE
    , RUN_SCHEDULE_START::TIMESTAMP_TZ          AS RUN_SCHEDULE_START
    , RUN_SCHEDULE_END::TIMESTAMP_TZ            AS RUN_SCHEDULE_END
    , VERSION_TAG::VARCHAR                      AS VERSION_TAG
    , DAILY_BUDGET_AMOUNT::FLOAT                AS DAILY_BUDGET_AMOUNT
    , DAILY_BUDGET_CURRENCY_CODE::VARCHAR       AS DAILY_BUDGET_CURRENCY_CODE
    , UNIT_COST_AMOUNT::FLOAT                   AS UNIT_COST_AMOUNT
    , UNIT_COST_CURRENCY_CODE::VARCHAR          AS UNIT_COST_CURRENCY_CODE
    , CAMPAIGN_GROUP_ID::VARCHAR                AS CAMPAIGN_GROUP_ID
    , ACCOUNT_ID::VARCHAR                       AS ACCOUNT_ID
    , CREATED_TIME::TIMESTAMP_TZ                AS PLATFORM_CREATED_AT
    , LAST_MODIFIED_TIME::TIMESTAMP_TZ          AS PLATFORM_UPDATED_AT
    , _FIVETRAN_SYNCED::TIMESTAMP_TZ            AS PROCESSED_AT
    , ROW_NUMBER() OVER (PARTITION BY ID ORDER BY _FIVETRAN_SYNCED DESC) AS ROW_NUM
  FROM "LINKEDIN_ADS"."CAMPAIGN_HISTORY"

)
WHERE ROW_NUM = 1
;