CREATE OR REPLACE VIEW GOOGLE_ANALYTICS_VIEWS.AFFINITY_CATEGORIES AS
	SELECT _FIVETRAN_SYNCED AS CREATED_AT
		, _FIVETRAN_SYNCED AS UPDATED_AT
--      Add universal ids later
-- 		, BLAH BLAH AS UNIVERSAL_ID
		, DATE
		, PROFILE AS PROFILE_ID
		, INTEREST_AFFINITY_CATEGORY
		, PAGEVIEWS
		, SESSIONS
		, PERCENT_NEW_SESSIONS
		, SESSION_DURATION
		, NEW_VISITS
		, BOUNCES
		, NEW_USERS
		, USERS
		, TRANSACTIONS
		, TRANSACTION_REVENUE
	FROM "GOOGLE_ANALYTICS"."AFFINITY_CATEGORIES"
;