CREATE OR REPLACE VIEW GOOGLE_ANALYTICS_VIEWS.AUDIENCE_AGE_GENDER AS
	SELECT _FIVETRAN_SYNCED AS CREATED_AT
		, _FIVETRAN_SYNCED AS UPDATED_AT
-- 		Add universal ids later
-- 		, BLAH BLAH AS UNIVERSAL_ID
		, DATE
		, PROFILE AS PROFILE_ID
		, USER_AGE_BRACKET
		, USER_GENDER
		, PAGEVIEWS
		, SESSIONS
		, PERCENT_NEW_SESSIONS
		, SESSION_DURATION
		, NEW_VISITS
		, BOUNCES
		, NEW_USERS
		, USERS
		, TRANSACTIONS
		, TRANSACTION_REVENUE
	FROM "GOOGLE_ANALYTICS"."AUDIENCE_AGE_GENDER"
;
