CREATE OR REPLACE VIEW GOOGLE_ANALYTICS_VIEWS.CAMPAIGN_CUSTOM_GOALS AS

SELECT CREATED_AT::TIMESTAMP_TZ                 AS CREATED_AT
        , UPDATED_AT::TIMESTAMP_TZ              AS UPDATED_AT
        , DATE::DATE                            AS DATE
        , PROFILE_ID::VARCHAR                   AS PROFILE_ID
        , CHANNEL_GROUPING::VARCHAR             AS CHANNEL_GROUPING
        , MEDIUM::VARCHAR                       AS MEDIUM
        , CAMPAIGN::VARCHAR                     AS CAMPAIGN
        , SESSIONS::DECIMAL(38, 0)              AS SESSIONS
        , GOAL_1_COMPLETIONS::DECIMAL(38, 0)    AS GOAL_1_COMPLETIONS
        , GOAL_1_VALUE::DECIMAL(30, 6)          AS GOAL_1_VALUE
        , GOAL_2_COMPLETIONS::DECIMAL(38, 0)    AS GOAL_2_COMPLETIONS
        , GOAL_2_VALUE::DECIMAL(30, 6)          AS GOAL_2_VALUE
        , GOAL_3_COMPLETIONS::DECIMAL(38, 0)    AS GOAL_3_COMPLETIONS
        , GOAL_3_VALUE::DECIMAL(30, 6)          AS GOAL_3_VALUE
        , GOAL_4_COMPLETIONS::DECIMAL(38, 0)    AS GOAL_4_COMPLETIONS
        , GOAL_4_VALUE::DECIMAL(30, 6)          AS GOAL_4_VALUE
        , GOAL_5_COMPLETIONS::DECIMAL(38, 0)    AS GOAL_5_COMPLETIONS
        , GOAL_5_VALUE::DECIMAL(30, 6)          AS GOAL_5_VALUE
        , GOAL_6_COMPLETIONS::DECIMAL(38, 0)    AS GOAL_6_COMPLETIONS
        , GOAL_6_VALUE::DECIMAL(30, 6)          AS GOAL_6_VALUE
        , GOAL_7_COMPLETIONS::DECIMAL(38, 0)    AS GOAL_7_COMPLETIONS
        , GOAL_7_VALUE::DECIMAL(30, 6)          AS GOAL_7_VALUE
        , GOAL_8_COMPLETIONS::DECIMAL(38, 0)    AS GOAL_8_COMPLETIONS
        , GOAL_8_VALUE::DECIMAL(30, 6)          AS GOAL_8_VALUE
        , GOAL_9_COMPLETIONS::DECIMAL(38, 0)    AS GOAL_9_COMPLETIONS
        , GOAL_9_VALUE::DECIMAL(30, 6)          AS GOAL_9_VALUE
        , GOAL_10_COMPLETIONS::DECIMAL(38, 0)   AS GOAL_10_COMPLETIONS
        , GOAL_10_VALUE::DECIMAL(30, 6)         AS GOAL_10_VALUE
        , GOAL_11_COMPLETIONS::DECIMAL(38, 0)   AS GOAL_11_COMPLETIONS
        , GOAL_11_VALUE::DECIMAL(30, 6)         AS GOAL_11_VALUE
        , GOAL_12_COMPLETIONS::DECIMAL(38, 0)   AS GOAL_12_COMPLETIONS
        , GOAL_12_VALUE::DECIMAL(30, 6)         AS GOAL_12_VALUE
        , GOAL_13_COMPLETIONS::DECIMAL(38, 0)   AS GOAL_13_COMPLETIONS
        , GOAL_13_VALUE::DECIMAL(30, 6)         AS GOAL_13_VALUE
        , GOAL_14_COMPLETIONS::DECIMAL(38, 0)   AS GOAL_14_COMPLETIONS
        , GOAL_14_VALUE::DECIMAL(30, 6)         AS GOAL_14_VALUE
        , GOAL_15_COMPLETIONS::DECIMAL(38, 0)   AS GOAL_15_COMPLETIONS
        , GOAL_15_VALUE::DECIMAL(30, 6)         AS GOAL_15_VALUE
        , GOAL_16_COMPLETIONS::DECIMAL(38, 0)   AS GOAL_16_COMPLETIONS
        , GOAL_16_VALUE::DECIMAL(30, 6)         AS GOAL_16_VALUE
FROM (
    SELECT DATE
      , PROFILE AS PROFILE_ID
      , CHANNEL_GROUPING
      , MEDIUM
      , CAMPAIGN
      , SUM(SESSIONS)               AS SESSIONS
      , MAX(_FIVETRAN_SYNCED)       AS CREATED_AT
      , MAX(_FIVETRAN_SYNCED)       AS UPDATED_AT    
      , SUM(GOAL_1_COMPLETIONS)     AS GOAL_1_COMPLETIONS
      , SUM(GOAL_1_VALUE)           AS GOAL_1_VALUE
      , SUM(GOAL_2_COMPLETIONS)     AS GOAL_2_COMPLETIONS
      , SUM(GOAL_2_VALUE)           AS GOAL_2_VALUE
      , SUM(GOAL_3_COMPLETIONS)     AS GOAL_3_COMPLETIONS
      , SUM(GOAL_3_VALUE)           AS GOAL_3_VALUE
      , SUM(GOAL_4_COMPLETIONS)     AS GOAL_4_COMPLETIONS
      , SUM(GOAL_4_VALUE)           AS GOAL_4_VALUE
    FROM "GOOGLE_ANALYTICS"."CAMPAIGN_CUSTOM_GOALS_1_4"
    GROUP BY 1,2,3,4,5
  
) AS ONE_FOUR
LEFT JOIN (

    SELECT DATE
      , PROFILE AS PROFILE_ID
      , CHANNEL_GROUPING
      , MEDIUM
      , CAMPAIGN
      , SUM(SESSIONS)               AS SESSIONS
      , MAX(_FIVETRAN_SYNCED)       AS CREATED_AT
      , MAX(_FIVETRAN_SYNCED)       AS UPDATED_AT    
      , SUM(GOAL_5_COMPLETIONS)     AS GOAL_5_COMPLETIONS
      , SUM(GOAL_5_VALUE)           AS GOAL_5_VALUE
      , SUM(GOAL_6_COMPLETIONS)     AS GOAL_6_COMPLETIONS
      , SUM(GOAL_6_VALUE)           AS GOAL_6_VALUE
      , SUM(GOAL_7_COMPLETIONS)     AS GOAL_7_COMPLETIONS
      , SUM(GOAL_7_VALUE)           AS GOAL_7_VALUE
      , SUM(GOAL_8_COMPLETIONS)     AS GOAL_8_COMPLETIONS
      , SUM(GOAL_8_VALUE)           AS GOAL_8_VALUE
    FROM "GOOGLE_ANALYTICS"."CAMPAIGN_CUSTOM_GOALS_5_8"
    GROUP BY 1,2,3,4,5

) AS FIVE_EIGHT
USING (DATE, PROFILE_ID, CHANNEL_GROUPING, MEDIUM, CAMPAIGN)
LEFT JOIN (

    SELECT DATE
      , PROFILE AS PROFILE_ID
      , CHANNEL_GROUPING
      , MEDIUM
      , CAMPAIGN
      , SUM(SESSIONS)               AS SESSIONS
      , MAX(_FIVETRAN_SYNCED)       AS CREATED_AT
      , MAX(_FIVETRAN_SYNCED)       AS UPDATED_AT    
      , SUM(GOAL_9_COMPLETIONS)     AS GOAL_9_COMPLETIONS
      , SUM(GOAL_9_VALUE)           AS GOAL_9_VALUE
      , SUM(GOAL_10_COMPLETIONS)     AS GOAL_10_COMPLETIONS
      , SUM(GOAL_10_VALUE)           AS GOAL_10_VALUE
      , SUM(GOAL_11_COMPLETIONS)     AS GOAL_11_COMPLETIONS
      , SUM(GOAL_11_VALUE)           AS GOAL_11_VALUE
      , SUM(GOAL_12_COMPLETIONS)     AS GOAL_12_COMPLETIONS
      , SUM(GOAL_12_VALUE)           AS GOAL_12_VALUE
    FROM "GOOGLE_ANALYTICS"."CAMPAIGN_CUSTOM_GOALS_9_12"
    GROUP BY 1,2,3,4,5

) AS NINE_TWELVE
USING (DATE, PROFILE_ID, CHANNEL_GROUPING, MEDIUM, CAMPAIGN)
LEFT JOIN (

    SELECT DATE
      , PROFILE AS PROFILE_ID
      , CHANNEL_GROUPING
      , MEDIUM
      , CAMPAIGN
      , SUM(SESSIONS)               AS SESSIONS
      , MAX(_FIVETRAN_SYNCED)       AS CREATED_AT
      , MAX(_FIVETRAN_SYNCED)       AS UPDATED_AT    
      , SUM(GOAL_13_COMPLETIONS)     AS GOAL_13_COMPLETIONS
      , SUM(GOAL_13_VALUE)           AS GOAL_13_VALUE
      , SUM(GOAL_14_COMPLETIONS)     AS GOAL_14_COMPLETIONS
      , SUM(GOAL_14_VALUE)           AS GOAL_14_VALUE
      , SUM(GOAL_15_COMPLETIONS)     AS GOAL_15_COMPLETIONS
      , SUM(GOAL_15_VALUE)           AS GOAL_15_VALUE
      , SUM(GOAL_16_COMPLETIONS)     AS GOAL_16_COMPLETIONS
      , SUM(GOAL_16_VALUE)           AS GOAL_16_VALUE
    FROM "GOOGLE_ANALYTICS"."CUSTOM_CAMPAIGN_GOALS_13_16"
    GROUP BY 1,2,3,4,5

) AS THIRTEEN_SIXTEEN
USING (DATE, PROFILE_ID, CHANNEL_GROUPING, MEDIUM, CAMPAIGN)
;
