CREATE OR REPLACE VIEW GOOGLE_ANALYTICS_VIEWS.PRODUCT_PERFORMANCE AS
	SELECT _FIVETRAN_SYNCED AS CREATED_AT
		, _FIVETRAN_SYNCED AS UPDATED_AT
-- 		Add universal id later
-- 		, BLAH BLAH AS UNIVERSAL_ID
		, DATE
		, PROFILE AS PROFILE_ID
		, PRODUCT_CATEGORY
		, PRODUCT_NAME
		, PRODUCT_SKU
		, ITEM_REVENUE
		, ITEM_QUANTITY
		, UNIQUE_PURCHASES
		, REVENUE_PER_ITEM
		, ITEMS_PER_PURCHASE
		, PRODUCT_ADDS_TO_CART
		, PRODUCT_DETAIL_VIEWS
		, PRODUCT_CHECKOUTS
	FROM "GOOGLE_ANALYTICS"."PRODUCT_PERFORMANCE"
;
