CREATE OR REPLACE VIEW GOOGLE_ANALYTICS_VIEWS.TOP_EVENTS AS
	SELECT _FIVETRAN_SYNCED AS CREATED_AT
		, _FIVETRAN_SYNCED AS UPDATED_AT
-- 		Add universal ids later
-- 		, BLAH BLAH AS UNIVERSAL_ID
		, DATE
		, PROFILE AS PROFILE_ID
		, EVENT_CATEGORY
		, EVENT_ACTION
		, EVENT_LABEL
		, TOTAL_EVENTS
		, UNIQUE_EVENTS
		, TOTAL_VALUE
		, AVG_EVENT_VALUE
		, SESSIONS_WITH_EVENT
		, EVENTS_PER_SESSION_WITH_EVENT
	FROM "GOOGLE_ANALYTICS"."TOP_EVENTS"
;
