CREATE OR REPLACE VIEW GOOGLE_ANALYTICS_VIEWS.TRAFFIC_SOURCES AS
	SELECT _FIVETRAN_SYNCED AS CREATED_AT
		, _FIVETRAN_SYNCED AS UPDATED_AT
-- 		Add universal ids later
-- 		, BLAH BLAH AS UNIVERSAL_ID
		, DATE
		, PROFILE AS PROFILE_ID
		, CHANNEL_GROUPING
--		, HAS_SOCIAL_SOURCE_REFERRAL
		, AD_CONTENT
		, MEDIUM
		, CAMPAIGN
		, SOURCE
		, SOCIAL_NETWORK
		, PAGEVIEWS
		, SESSIONS
		, PERCENT_NEW_SESSIONS
		, SESSION_DURATION
		, NEW_VISITS
		, BOUNCES
		, NEW_USERS
		, USERS
		, TRANSACTIONS
		, TRANSACTION_REVENUE
	FROM "GOOGLE_ANALYTICS"."TRAFFIC_SOURCES"
;