CREATE OR REPLACE VIEW "ADWORDS_VIEWS"."ENTITY_CAMPAIGNS" AS

SELECT

    CUSTOMER_ID
    , AD_SERVING_OPTIMIZATION_STATUS
    , ADVERTISING_CHANNEL_SUBTYPE
    , ADVERTISING_CHANNEL_TYPE
    , BASE_CAMPAIGN_ID
    , CAMPAIGN_ID
    , CAMPAIGN_NAME
    , CAMPAIGN_GROUP_ID
    , CAMPAIGN_TRIAL_TYPE
    , CAMPAIGN_SERVING_STATUS
    , CAMPAIGN_STATUS
    , CAMPAIGN_START_DATE
    , CAMPAIGN_END_DATE
    , FREQUENCY_CAP_IMPRESSIONS
    , FREQUENCY_CAP_LEVEL
    , FREQUENCY_CAP_TIME_UNIT
    , NETWORK_SETTING_TARGET_CONTENT_NETWORK
    , NETWORK_SETTING_TARGET_GOOGLE_SEARCH
    , NETWORK_SETTING_TARGET_PARTNER_SEARCH_NETWORK
    , NETWORK_SETTING_TARGET_SEARCH_NETWORK
    , FINAL_URL_SUFFIX
    , TRACKING_URL_TEMPLATE
    , VANITY_PHARMA_DISPLAY_URL_MODE
    , VANITY_PHARMA_TEXT
    , BIDDING_STRATEGY_SCHEME_TYPE
    , BIDDING_STRATEGY_BID_CEILING
    , BIDDING_STRATEGY_BID_CHANGES_FOR_RAISES_ONLY
    , BIDDING_STRATEGY_BID_FLOOR
    , BIDDING_STRATEGY_BID_MODIFIER
    , BIDDING_STRATEGY_COMPETITOR_DOMAIN
    , BIDDING_STRATEGY_ENHANCED_CPC_ENABLED
    , BIDDING_STRATEGY_ID
    , BIDDING_STRATEGY_MAX_CPC_BID_CEILING
    , BIDDING_STRATEGY_MAX_CPC_BID_FLOOR
    , BIDDING_STRATEGY_NAME
    , BIDDING_STRATEGY_RAISE_BID_WHEN_BUDGET_CONSTRAINED
    , BIDDING_STRATEGY_RAISE_BID_WHEN_LOW_QUALITY_SCORE
    , BIDDING_STRATEGY_SOURCE
    , BIDDING_STRATEGY_SPEND_TARGET
    , BIDDING_STRATEGY_STRATEGY_GOAL
    , BIDDING_STRATEGY_TARGET_CPA
    , BIDDING_STRATEGY_TARGET_OUTRANK_SHARE
    , BIDDING_STRATEGY_TARGET_ROAS
    , BIDDING_STRATEGY_TARGET_ROAS_OVERRIDE
    , BIDDING_STRATEGY_TYPE
    , BIDDING_STRATEGY_VIEWABLE_CPM_ENABLED
    , BIDDING_STRATEGY_CPA_BID_AMOUNT
    , BIDDING_STRATEGY_CPC_BID_AMOUNT
    , BIDDING_STRATEGY_CPM_BID_AMOUNT
    , UPDATED_AT

FROM (

  SELECT 
      CUSTOMER_ID::VARCHAR                                                  AS CUSTOMER_ID
      , AD_SERVING_OPTIMIZATION_STATUS::VARCHAR(256)                        AS AD_SERVING_OPTIMIZATION_STATUS
      , ADVERTISING_CHANNEL_SUBTYPE::VARCHAR(256)                           AS ADVERTISING_CHANNEL_SUBTYPE
      , ADVERTISING_CHANNEL_TYPE::VARCHAR(256)                              AS ADVERTISING_CHANNEL_TYPE
      , BASE_CAMPAIGN_ID::VARCHAR                                           AS BASE_CAMPAIGN_ID
      , ID::VARCHAR                                                         AS CAMPAIGN_ID
      , NAME::VARCHAR(256)                                                  AS CAMPAIGN_NAME
      , CAMPAIGN_GROUP_ID::VARCHAR                                          AS CAMPAIGN_GROUP_ID
      , CAMPAIGN_TRIAL_TYPE::VARCHAR(256)                                   AS CAMPAIGN_TRIAL_TYPE
      , SERVING_STATUS::VARCHAR(256)                                        AS CAMPAIGN_SERVING_STATUS
      , STATUS::VARCHAR(256)                                                AS CAMPAIGN_STATUS
      , START_DATE::VARCHAR(256)                                            AS CAMPAIGN_START_DATE
      , END_DATE::VARCHAR(256)                                              AS CAMPAIGN_END_DATE
      , FREQUENCY_CAP_IMPRESSIONS::NUMBER(38,0)                             AS FREQUENCY_CAP_IMPRESSIONS
      , FREQUENCY_CAP_LEVEL::VARCHAR(256)                                   AS FREQUENCY_CAP_LEVEL
      , FREQUENCY_CAP_TIME_UNIT::VARCHAR(256)                               AS FREQUENCY_CAP_TIME_UNIT
      , NETWORK_SETTING_TARGET_CONTENT_NETWORK::BOOLEAN                     AS NETWORK_SETTING_TARGET_CONTENT_NETWORK
      , NETWORK_SETTING_TARGET_GOOGLE_SEARCH::BOOLEAN                       AS NETWORK_SETTING_TARGET_GOOGLE_SEARCH
      , NETWORK_SETTING_TARGET_PARTNER_SEARCH_NETWORK::BOOLEAN              AS NETWORK_SETTING_TARGET_PARTNER_SEARCH_NETWORK
      , NETWORK_SETTING_TARGET_SEARCH_NETWORK::BOOLEAN                      AS NETWORK_SETTING_TARGET_SEARCH_NETWORK
      , FINAL_URL_SUFFIX::VARCHAR(256)                                      AS FINAL_URL_SUFFIX
      , TRACKING_URL_TEMPLATE::VARCHAR(512)                                 AS TRACKING_URL_TEMPLATE
      , VANITY_PHARMA_DISPLAY_URL_MODE::VARCHAR(256)                        AS VANITY_PHARMA_DISPLAY_URL_MODE
      , VANITY_PHARMA_TEXT::VARCHAR(256)                                    AS VANITY_PHARMA_TEXT
      , BIDDING_STRATEGY_SCHEME_TYPE::VARCHAR(256)                          AS BIDDING_STRATEGY_SCHEME_TYPE
      , BIDDING_STRATEGY_BID_CEILING::NUMBER(38,0)                          AS BIDDING_STRATEGY_BID_CEILING
      , BIDDING_STRATEGY_BID_CHANGES_FOR_RAISES_ONLY::BOOLEAN               AS BIDDING_STRATEGY_BID_CHANGES_FOR_RAISES_ONLY
      , BIDDING_STRATEGY_BID_FLOOR::NUMBER(38,0)                            AS BIDDING_STRATEGY_BID_FLOOR
      , BIDDING_STRATEGY_BID_MODIFIER::FLOAT                                AS BIDDING_STRATEGY_BID_MODIFIER
      , BIDDING_STRATEGY_COMPETITOR_DOMAIN::VARCHAR(256)                    AS BIDDING_STRATEGY_COMPETITOR_DOMAIN
      , BIDDING_STRATEGY_ENHANCED_CPC_ENABLED::BOOLEAN                      AS BIDDING_STRATEGY_ENHANCED_CPC_ENABLED
      , BIDDING_STRATEGY_ID::VARCHAR                                        AS BIDDING_STRATEGY_ID
      , BIDDING_STRATEGY_MAX_CPC_BID_CEILING::NUMBER(38,0)                  AS BIDDING_STRATEGY_MAX_CPC_BID_CEILING
      , BIDDING_STRATEGY_MAX_CPC_BID_FLOOR::NUMBER(38,0)                    AS BIDDING_STRATEGY_MAX_CPC_BID_FLOOR
      , BIDDING_STRATEGY_NAME::VARCHAR(256)                                 AS BIDDING_STRATEGY_NAME
      , BIDDING_STRATEGY_RAISE_BID_WHEN_BUDGET_CONSTRAINED::BOOLEAN         AS BIDDING_STRATEGY_RAISE_BID_WHEN_BUDGET_CONSTRAINED
      , BIDDING_STRATEGY_RAISE_BID_WHEN_LOW_QUALITY_SCORE::BOOLEAN          AS BIDDING_STRATEGY_RAISE_BID_WHEN_LOW_QUALITY_SCORE
      , BIDDING_STRATEGY_SOURCE::VARCHAR(256)                               AS BIDDING_STRATEGY_SOURCE
      , BIDDING_STRATEGY_SPEND_TARGET::NUMBER(38,0)                         AS BIDDING_STRATEGY_SPEND_TARGET
      , BIDDING_STRATEGY_STRATEGY_GOAL::VARCHAR(256)                        AS BIDDING_STRATEGY_STRATEGY_GOAL
      , BIDDING_STRATEGY_TARGET_CPA::NUMBER(38,0)                           AS BIDDING_STRATEGY_TARGET_CPA
      , BIDDING_STRATEGY_TARGET_OUTRANK_SHARE::NUMBER(38,0)                 AS BIDDING_STRATEGY_TARGET_OUTRANK_SHARE
      , BIDDING_STRATEGY_TARGET_ROAS::FLOAT                                 AS BIDDING_STRATEGY_TARGET_ROAS
      , BIDDING_STRATEGY_TARGET_ROAS_OVERRIDE::FLOAT                        AS BIDDING_STRATEGY_TARGET_ROAS_OVERRIDE
      , BIDDING_STRATEGY_TYPE::VARCHAR(256)                                 AS BIDDING_STRATEGY_TYPE
      , BIDDING_STRATEGY_VIEWABLE_CPM_ENABLED::BOOLEAN                      AS BIDDING_STRATEGY_VIEWABLE_CPM_ENABLED
      , BIDDING_STRATEGY_CPA_BID_AMOUNT::NUMBER(38,0)                       AS BIDDING_STRATEGY_CPA_BID_AMOUNT
      , BIDDING_STRATEGY_CPC_BID_AMOUNT::NUMBER(38,0)                       AS BIDDING_STRATEGY_CPC_BID_AMOUNT
      , BIDDING_STRATEGY_CPM_BID_AMOUNT::NUMBER(38,0)                       AS BIDDING_STRATEGY_CPM_BID_AMOUNT  
      , UPDATED_AT::TIMESTAMP_TZ(9)                                         AS UPDATED_AT
      , _FIVETRAN_SYNCED::TIMESTAMP_TZ(9)
      , ROW_NUMBER() OVER (PARTITION BY ID ORDER BY _FIVETRAN_SYNCED DESC) AS ROW_NUM

  FROM "GOOGLE_ADS_ACCOUNT"."CAMPAIGN_HISTORY"
)
WHERE ROW_NUM = 1
;