CREATE OR REPLACE VIEW "ADWORDS_VIEWS"."ENTITY_AD_GROUPS" AS

SELECT

    AD_GROUP_ID
    , AD_GROUP_NAME
    , AD_GROUP_STATUS
    , AD_GROUP_TYPE
    , AD_GROUP_ROTATION_MODE
    , BASE_AD_GROUP_ID
    , BASE_CAMPAIGN_ID
    , CAMPAIGN_ID
    , BIDDING_STRATEGY_SCHEME_TYPE
    , BIDDING_STRATEGY_BID_CEILING
    , BIDDING_STRATEGY_BID_CHANGES_FOR_RAISES_ONLY
    , BIDDING_STRATEGY_BID_FLOOR
    , BIDDING_STRATEGY_BID_MODIFIER
    , BIDDING_STRATEGY_COMPETITOR_DOMAIN
    , BIDDING_STRATEGY_ENHANCED_CPC_ENABLED
    , BIDDING_STRATEGY_ID
    , BIDDING_STRATEGY_MAX_CPC_BID_CEILING
    , BIDDING_STRATEGY_MAX_CPC_BID_FLOOR
    , BIDDING_STRATEGY_NAME
    , BIDDING_STRATEGY_RAISE_BID_WHEN_BUDGET_CONSTRAINED
    , BIDDING_STRATEGY_RAISE_BID_WHEN_LOW_QUALITY_SCORE
    , BIDDING_STRATEGY_SOURCE
    , BIDDING_STRATEGY_SPEND_TARGET
    , BIDDING_STRATEGY_STRATEGY_GOAL
    , BIDDING_STRATEGY_TARGET_CPA
    , BIDDING_STRATEGY_TARGET_OUTRANK_SHARE
    , BIDDING_STRATEGY_TARGET_ROAS
    , BIDDING_STRATEGY_TARGET_ROAS_OVERRIDE
    , BIDDING_STRATEGY_TYPE
    , BIDDING_STRATEGY_VIEWABLE_CPM_ENABLED
    , BIDDING_STRATEGY_CPA_BID_AMOUNT
    , BIDDING_STRATEGY_CPC_BID_AMOUNT
    , BIDDING_STRATEGY_CPM_BID_AMOUNT
    , CONTENT_BID_CRITERION_TYPE_GROUP
    , FINAL_URL_SUFFIX
    , TRACKING_URL_TEMPLATE
    , UPDATED_AT

FROM (

  SELECT 

      ID::VARCHAR                                                             AS AD_GROUP_ID
      , NAME::VARCHAR(256)                                                    AS AD_GROUP_NAME
      , STATUS::VARCHAR(256)                                                  AS AD_GROUP_STATUS
      , AD_GROUP_TYPE::VARCHAR(256)                                           AS AD_GROUP_TYPE
      , AD_GROUP_ROTATION_MODE::VARCHAR(256)                                  AS AD_GROUP_ROTATION_MODE
      , BASE_AD_GROUP_ID::VARCHAR                                             AS BASE_AD_GROUP_ID
      , BASE_CAMPAIGN_ID::VARCHAR                                             AS BASE_CAMPAIGN_ID
      , CAMPAIGN_ID::VARCHAR                                                  AS CAMPAIGN_ID
      , BIDDING_STRATEGY_SCHEME_TYPE::VARCHAR(256)                            AS BIDDING_STRATEGY_SCHEME_TYPE
      , BIDDING_STRATEGY_BID_CEILING::NUMBER(38,0)                            AS BIDDING_STRATEGY_BID_CEILING
      , BIDDING_STRATEGY_BID_CHANGES_FOR_RAISES_ONLY::BOOLEAN                 AS BIDDING_STRATEGY_BID_CHANGES_FOR_RAISES_ONLY
      , BIDDING_STRATEGY_BID_FLOOR::NUMBER(38,0)                              AS BIDDING_STRATEGY_BID_FLOOR
      , BIDDING_STRATEGY_BID_MODIFIER::FLOAT                                  AS BIDDING_STRATEGY_BID_MODIFIER
      , BIDDING_STRATEGY_COMPETITOR_DOMAIN::VARCHAR(256)                      AS BIDDING_STRATEGY_COMPETITOR_DOMAIN
      , BIDDING_STRATEGY_ENHANCED_CPC_ENABLED::BOOLEAN                        AS BIDDING_STRATEGY_ENHANCED_CPC_ENABLED
      , BIDDING_STRATEGY_ID::VARCHAR                                          AS BIDDING_STRATEGY_ID
      , BIDDING_STRATEGY_MAX_CPC_BID_CEILING::NUMBER(38,0)                    AS BIDDING_STRATEGY_MAX_CPC_BID_CEILING
      , BIDDING_STRATEGY_MAX_CPC_BID_FLOOR::NUMBER(38,0)                      AS BIDDING_STRATEGY_MAX_CPC_BID_FLOOR
      , BIDDING_STRATEGY_NAME::VARCHAR(256)                                   AS BIDDING_STRATEGY_NAME
      , BIDDING_STRATEGY_RAISE_BID_WHEN_BUDGET_CONSTRAINED::BOOLEAN           AS BIDDING_STRATEGY_RAISE_BID_WHEN_BUDGET_CONSTRAINED
      , BIDDING_STRATEGY_RAISE_BID_WHEN_LOW_QUALITY_SCORE::BOOLEAN            AS BIDDING_STRATEGY_RAISE_BID_WHEN_LOW_QUALITY_SCORE
      , BIDDING_STRATEGY_SOURCE::VARCHAR(256)                                 AS BIDDING_STRATEGY_SOURCE
      , BIDDING_STRATEGY_SPEND_TARGET::NUMBER(38,0)                           AS BIDDING_STRATEGY_SPEND_TARGET
      , BIDDING_STRATEGY_STRATEGY_GOAL::VARCHAR(256)                          AS BIDDING_STRATEGY_STRATEGY_GOAL
      , BIDDING_STRATEGY_TARGET_CPA::NUMBER(38,0)                             AS BIDDING_STRATEGY_TARGET_CPA
      , BIDDING_STRATEGY_TARGET_OUTRANK_SHARE::NUMBER(38,0)                   AS BIDDING_STRATEGY_TARGET_OUTRANK_SHARE
      , BIDDING_STRATEGY_TARGET_ROAS::FLOAT                                   AS BIDDING_STRATEGY_TARGET_ROAS
      , BIDDING_STRATEGY_TARGET_ROAS_OVERRIDE::FLOAT                          AS BIDDING_STRATEGY_TARGET_ROAS_OVERRIDE
      , BIDDING_STRATEGY_TYPE::VARCHAR(256)                                   AS BIDDING_STRATEGY_TYPE
      , BIDDING_STRATEGY_VIEWABLE_CPM_ENABLED::BOOLEAN                        AS BIDDING_STRATEGY_VIEWABLE_CPM_ENABLED
      , BIDDING_STRATEGY_CPA_BID_AMOUNT::NUMBER(38,0)                         AS BIDDING_STRATEGY_CPA_BID_AMOUNT
      , BIDDING_STRATEGY_CPC_BID_AMOUNT::NUMBER(38,0)                         AS BIDDING_STRATEGY_CPC_BID_AMOUNT
      , BIDDING_STRATEGY_CPM_BID_AMOUNT::NUMBER(38,0)                         AS BIDDING_STRATEGY_CPM_BID_AMOUNT
  --    , CAMPAIGN_NAME::VARCHAR(256)
      , CONTENT_BID_CRITERION_TYPE_GROUP::VARCHAR(256)                        AS CONTENT_BID_CRITERION_TYPE_GROUP
      , FINAL_URL_SUFFIX::VARCHAR(256)                                        AS FINAL_URL_SUFFIX
      , TRACKING_URL_TEMPLATE::VARCHAR(256)                                   AS TRACKING_URL_TEMPLATE
      , UPDATED_AT::TIMESTAMP_TZ(9)                                           AS UPDATED_AT
      , _FIVETRAN_SYNCED::TIMESTAMP_TZ(9)
      , ROW_NUMBER() OVER (PARTITION BY ID ORDER BY _FIVETRAN_SYNCED DESC) AS ROW_NUM

  FROM "GOOGLE_ADS_ACCOUNT"."AD_GROUP_HISTORY"
)
WHERE ROW_NUM = 1
;