CREATE OR REPLACE VIEW "ADWORDS_VIEWS"."METRIC_CREATIVES_DAILY_BY_SEARCH_QUERY" AS

SELECT

    CUSTOMER_ID::VARCHAR                        AS CUSTOMER_ID
    , CAMPAIGN_ID::VARCHAR                      AS CAMPAIGN_ID
    , AD_GROUP_ID::VARCHAR                      AS AD_GROUP_ID
    , CREATIVE_ID::VARCHAR                      AS CREATIVE_ID
    , AD_NETWORK_TYPE_1::VARCHAR(256)           AS AD_NETWORK_TYPE_1
    , AD_NETWORK_TYPE_2::VARCHAR(256)           AS AD_NETWORK_TYPE_2
    , AD_FORMAT::VARCHAR(256)                   AS AD_FORMAT
    , KEYWORD_ID::VARCHAR                       AS KEYWORD_ID
    , KEYWORD_TEXT_MATCHING_QUERY::VARCHAR(256) AS KEYWORD_TEXT_MATCHING_QUERY
    , QUERY::VARCHAR(256)                       AS SEARCH_TERM
    , DATE::DATE                                AS DATE
    
    , _FIVETRAN_ID::VARCHAR(256)                AS _FIVETRAN_ID
    , _FIVETRAN_SYNCED::TIMESTAMP_TZ(9)         AS _FIVETRAN_SYNCED
--    , ACCOUNT_CURRENCY_CODE::VARCHAR(256)       AS ACCOUNT_CURRENCY_CODE
--    , ACCOUNT_TIME_ZONE::VARCHAR(256)           AS ACCOUNT_TIME_ZONE

    , COST::FLOAT                               AS COST
    , ENGAGEMENTS::NUMBER(38,0)                 AS ENGAGEMENTS
    , IMPRESSIONS::NUMBER(38,0)                 AS IMPRESSIONS
    , CLICKS::NUMBER(38,0)                      AS CLICKS
    , INTERACTIONS::NUMBER(38,0)                AS INTERACTIONS
    , ABSOLUTE_TOP_IMPRESSION_PERCENTAGE::FLOAT AS ABSOLUTE_TOP_IMPRESSION_PERCENTAGE

    , VIDEO_QUARTILE_100_RATE::FLOAT            AS VIDEO_QUARTILE_100_RATE
    , VIDEO_QUARTILE_25_RATE::FLOAT             AS VIDEO_QUARTILE_25_RATE
    , VIDEO_QUARTILE_50_RATE::FLOAT             AS VIDEO_QUARTILE_50_RATE
    , VIDEO_QUARTILE_75_RATE::FLOAT             AS VIDEO_QUARTILE_75_RATE
    , VIDEO_VIEW_RATE::FLOAT                    AS VIDEO_VIEW_RATE
    , VIDEO_VIEWS::NUMBER(38,0)                 AS VIDEO_VIEWS

    , CONVERSIONS::FLOAT                        AS CONVERSIONS
    , CONVERSION_VALUE::FLOAT                   AS CONVERSION_VALUE
    , ALL_CONVERSIONS::FLOAT                    AS ALL_CONVERSIONS
    , ALL_CONVERSION_VALUE::FLOAT               AS ALL_CONVERSION_VALUE
    , CROSS_DEVICE_CONVERSIONS::FLOAT           AS CROSS_DEVICE_CONVERSIONS
    , VALUE_PER_ALL_CONVERSION::FLOAT           AS VALUE_PER_ALL_CONVERSION
    , VALUE_PER_CONVERSION::FLOAT               AS VALUE_PER_CONVERSION
    , VIEW_THROUGH_CONVERSIONS::NUMBER(38,0)    AS VIEW_THROUGH_CONVERSIONS

FROM "ADWORDS"."SEARCH_QUERY_PERFORMANCE_REPORT"
;