CREATE OR REPLACE VIEW "DOUBLECLICK_CAMPAIGN_MANAGER_VIEWS"."ENTITY_ADS" AS
SELECT ACCOUNT_ID::VARCHAR          AS ADVERTISER_ID
       , CAMPAIGN_ID::VARCHAR       AS CAMPAIGN_ID
       , SITE_KEYNAME::VARCHAR      AS SITE_KEYNAME
       , SITE_ID_DCM_::VARCHAR      AS SITE_ID
       , SITE_DCM_::VARCHAR         AS SITE
       , PLACEMENT_ID::VARCHAR      AS PLACEMENT_ID
       , AD_ID::VARCHAR             AS AD_ID
--     , AD::VARCHAR                AS AD
FROM (SELECT *,
             ROW_NUMBER() OVER (PARTITION BY
               ACCOUNT_ID,
               AD_ID
               ORDER BY _FIVETRAN_SYNCED DESC) ___R
      FROM "DOUBLE_CLICK_CAMPAIGN_MANAGER"."GENERAL_METRICS_MAIN_ACCOUNT"
      where AD_ID is not null
     ) DT
where DT.___R = 1;
