CREATE OR REPLACE VIEW "DOUBLECLICK_CAMPAIGN_MANAGER_VIEWS"."ENTITY_CAMPAIGNS" AS
SELECT ACCOUNT_ID::VARCHAR          AS ADVERTISER_ID
       , CAMPAIGN_ID::VARCHAR       AS CAMPAIGN_ID
       , ADVERTISER::VARCHAR        AS ADVERTISER
       , CAMPAIGN::VARCHAR          AS CAMPAIGN
FROM (SELECT *,
             ROW_NUMBER() OVER (PARTITION BY
               ACCOUNT_ID,
               CAMPAIGN_ID
               ORDER BY _FIVETRAN_SYNCED DESC) ___R
      FROM "DOUBLE_CLICK_CAMPAIGN_MANAGER"."GENERAL_METRICS_MAIN_ACCOUNT"
     ) DT
where DT.___R = 1;
